Repository microsoft/azure-pipelines-tasks, pull requests merged in 2018-06, with the labels that each got.

#7216 [SqlAzureDacpacDeployment] Add support for additional SqlPackage.exe actions.
  Tasks/SqlAzureDacpacDeploymentV1/DeploySqlAzure.ps1
  Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/SqlAzureDacpacDeploymentV1/Tests/L0.ts
  Tasks/SqlAzureDacpacDeploymentV1/Tests/L0DacpacTaskFileCheck.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Tests/L0SqlAzureActionsUtilityTests.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Tests/L0SqlPackageActions.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Tests/L0SqlcmdTests.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Tests/L0UtilityGetSqlCmdArgs.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Tests/L0ValidDacpacInput.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Tests/L0ValidSqlAzureInputs.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Tests/MockVariable.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Utility.ps1
  Tasks/SqlAzureDacpacDeploymentV1/task.json
  Tasks/SqlAzureDacpacDeploymentV1/task.loc.json
Labels: Area: Release

#7380 Azure stack - URL populate Fix
  Tasks/AzureAppServiceManageV0/task.json
  Tasks/AzureAppServiceManageV0/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-endpoint.ts
Labels: Area: AzureAppService, Area: Release

#7374 Updating tasks to their latest version for pagination
  Tasks/DownloadBuildArtifactsV0/task.json
  Tasks/DownloadBuildArtifactsV0/task.loc.json
  Tasks/VsTestV2/task.json
  Tasks/VsTestV2/task.loc.json
Labels: Area: Release

#7361 Added functionality to create a kubeconfig for Service account auth scheme
  Tasks/Common/utility-common/kubectlutility.ts
  Tasks/Common/utility-common/package.json
  Tasks/HelmDeployV0/make.json
  Tasks/HelmDeployV0/package.json
  Tasks/HelmDeployV0/src/clusters/generickubernetescluster.ts
  Tasks/HelmDeployV0/task.json
  Tasks/HelmDeployV0/task.loc.json
  Tasks/KubernetesV0/Tests/L0.ts
  Tasks/KubernetesV0/Tests/TestSetup.ts
  Tasks/KubernetesV0/Tests/TestShared.ts
  Tasks/KubernetesV0/make.json
  Tasks/KubernetesV0/src/clusterconnection.ts
  Tasks/KubernetesV0/task.json
  Tasks/KubernetesV0/task.loc.json
  Tasks/KubernetesV1/Tests/L0.ts
  Tasks/KubernetesV1/Tests/TestSetup.ts
  Tasks/KubernetesV1/Tests/TestShared.ts
  Tasks/KubernetesV1/src/clusters/generickubernetescluster.ts
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
Labels: Area: Release

#7335 allow user to upgrade service manifest without upgrading code or config
  Tasks/ServiceFabricDeployV1/Create-DiffPackage.psm1
  Tasks/ServiceFabricDeployV1/task.json
  Tasks/ServiceFabricDeployV1/task.loc.json
Labels: Area: Release, Area: ServiceFabric

#7396 Azure SQL task - fit and finish
  Tasks/SqlAzureDacpacDeploymentV1/DeploySqlAzure.ps1
  Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/SqlAzureDacpacDeploymentV1/task.json
  Tasks/SqlAzureDacpacDeploymentV1/task.loc.json
  package-lock.json
Labels: Area: Release

#7401 Azure SQL task - fit and finish (#7396)
  Tasks/SqlAzureDacpacDeploymentV1/DeploySqlAzure.ps1
  Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/SqlAzureDacpacDeploymentV1/task.json
  Tasks/SqlAzureDacpacDeploymentV1/task.loc.json
  package-lock.json
Labels: Area: Release

#7146 retry interval exponential
  Tasks/Common/azure-arm-rest/webClient.ts
Labels: Area: Release

#7110 mentioning setvariable is scoped to the current phase
  docs/authoring/commands.md
Labels: Area: Release

#7262 Azure App Service Deploy - Perf Improvements & ZipDeploy - RunFromZip feature
  Tasks/AzureAppServiceManageV0/operations/KuduServiceUtils.ts
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/Tests/L0.ts
  Tasks/AzureRmWebAppDeploymentV4/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/AzureRmWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/DeploymentFactory.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppRunFromZipProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppWebDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/KuduServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/WebDeployUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/webdeployment-common/Tests/L0MSDeployUtility.ts
  Tasks/Common/webdeployment-common/deployusingmsdeploy.ts
  Tasks/Common/webdeployment-common/msdeployutility.ts
  Tasks/Common/webdeployment-common/packageUtility.ts
Labels: Area: AzureAppService, Area: Release

#7453 Azure stack URL populate fix M135
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
  Tasks/AzureResourceGroupDeploymentV2/task.json
  Tasks/AzureResourceGroupDeploymentV2/task.loc.json
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-endpoint.ts
Labels: Area: AzureAppService, Area: Release

#7450 Azure Stack populate URL fix TFS 2018 U3
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
  Tasks/AzureResourceGroupDeployment/task.json
  Tasks/AzureResourceGroupDeployment/task.loc.json
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-endpoint.ts
Labels: Area: AzureAppService, Area: Release

#7451 Azure Stack populate URL fix M131
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
  Tasks/AzureResourceGroupDeployment/task.json
  Tasks/AzureResourceGroupDeployment/task.loc.json
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-endpoint.ts
Labels: Area: AzureAppService, Area: Release

#7379 Add DownloadFileShare Artifacts task
  Tasks/DownloadBuildArtifactsV0/main.ts
  Tasks/DownloadBuildArtifactsV0/task.json
  Tasks/DownloadBuildArtifactsV0/task.loc.json
  Tasks/DownloadFileshareArtifactsV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DownloadFileshareArtifactsV0/ThirdPartyNotices.txt
  Tasks/DownloadFileshareArtifactsV0/icon.png
  Tasks/DownloadFileshareArtifactsV0/icon.svg
  Tasks/DownloadFileshareArtifactsV0/main.ts
  Tasks/DownloadFileshareArtifactsV0/package-lock.json
  Tasks/DownloadFileshareArtifactsV0/package.json
  Tasks/DownloadFileshareArtifactsV0/task.json
  Tasks/DownloadFileshareArtifactsV0/task.loc.json
  Tasks/DownloadFileshareArtifactsV0/tsconfig.json
  Tasks/DownloadFileshareArtifactsV0/typings.json
  make-options.json
Labels: Area: Release

#7468 In getImageNames, changed new line replace text from string to regex.
  Tasks/DockerV0/task.json
  Tasks/DockerV0/task.loc.json
  Tasks/DockerV0/utils.ts
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
  Tasks/DockerV1/utils.ts
Labels: Area: Release

#7444 Import-Module AzureRM fails with The TypeConverter was ignored because it already occurs
  Tasks/Common/VstsAzureHelpers_/ImportFunctions.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromSdkPath.ImportsModule.ps1
Labels: Area: Release

#7497 App service Perf. Improvements Fix
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/KuduServiceUtility.ts
  Tasks/Common/azure-arm-rest/azure-arm-app-service.ts
Labels: Area: AzureAppService, Area: Release

#7474 Added telemetries
  Tasks/Common/Deployment/TelemetryHelper/TelemetryHelper.psm1
  Tasks/Common/PowershellHelpers/Helpers.ps1
  Tasks/Common/ServiceFabricHelpers/Connect-ServiceFabricClusterFromServiceEndpoint.ps1
  Tasks/Common/ServiceFabricHelpers/Get-ServiceFabricEncryptedText.ps1
  Tasks/Common/ServiceFabricHelpers/SFOperations.ps1
  Tasks/Common/ServiceFabricHelpers/ServiceFabricHelpers.psm1
  Tasks/ServiceFabricComposeDeployV0/ServiceFabricComposeDeploy.ps1
  Tasks/ServiceFabricComposeDeployV0/make.json
  Tasks/ServiceFabricComposeDeployV0/task.json
  Tasks/ServiceFabricComposeDeployV0/task.loc.json
  Tasks/ServiceFabricComposeDeployV0/utilities.ps1
  Tasks/ServiceFabricDeployV1/ServiceFabricSDK/Publish-NewServiceFabricApplication.ps1
  Tasks/ServiceFabricDeployV1/ServiceFabricSDK/Publish-UpgradedServiceFabricApplication.ps1
  Tasks/ServiceFabricDeployV1/ServiceFabricSDK/Utilities.ps1
  Tasks/ServiceFabricDeployV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/ServiceFabricDeployV1/deploy.ps1
  Tasks/ServiceFabricDeployV1/make.json
  Tasks/ServiceFabricDeployV1/task.json
  Tasks/ServiceFabricDeployV1/task.loc.json
  Tasks/ServiceFabricPowerShellV1/ServiceFabricPowerShell.ps1
  Tasks/ServiceFabricPowerShellV1/make.json
  Tasks/ServiceFabricPowerShellV1/task.json
  Tasks/ServiceFabricPowerShellV1/task.loc.json
Labels: Area: Release

#7438 change in post deployment execution
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/operations/KuduServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeploymentV4/postDeploymentScript/deleteLogFile.cmd
  Tasks/AzureRmWebAppDeploymentV4/postDeploymentScript/deleteLogFile.sh
  Tasks/AzureRmWebAppDeploymentV4/postDeploymentScript/mainCmdFile.cmd
  Tasks/AzureRmWebAppDeploymentV4/postDeploymentScript/mainCmdFile.sh
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/azure-arm-rest/module.json
Labels: Area: AzureAppService, Area: Release

#7394 Added default labels to the build image
  Tasks/DockerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerV1/containerbuild.ts
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
Labels: Area: Release

#7506 Users/arjgupta/af cv2 use response file
  Tasks/AzureFileCopyV2/PreJobExecutionAzureFileCopy.ts
  Tasks/AzureFileCopyV2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFileCopyV2/Tests/L0UploadFilesToAzureContainer.ps1
  Tasks/AzureFileCopyV2/Utility.ps1
  Tasks/AzureFileCopyV2/make.json
  Tasks/AzureFileCopyV2/package-lock.json
  Tasks/AzureFileCopyV2/package.json
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
Labels: Area: Release

#7458 Added scope of Management Group to service endpoint and resulting changes in powershell tasks.
  Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1
Labels: Area: Release

#7535 Time out fix
  Tasks/DownloadBuildArtifactsV0/task.json
  Tasks/DownloadBuildArtifactsV0/task.loc.json
  Tasks/DownloadBuildArtifactsV0/vso-node-api/VsoClient.ts
Labels: Area: Release

#7554 Populate default helm releaseName for upgrade
  Tasks/HelmDeployV0/src/helmcommands/helmupgrade.ts
  Tasks/HelmDeployV0/task.json
  Tasks/HelmDeployV0/task.loc.json
Labels: Area: Release
