Repository microsoft/azure-pipelines-tasks, pull requests merged in 2018-12, with the labels that each got.

#8994 Users/suaggar/app service telemetry
  Tasks/AzureFunctionDeploymentV1/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureFunctionDeploymentV1/deploymentProvider/DeploymentFactory.ts
  Tasks/AzureFunctionDeploymentV1/deploymentProvider/WindowsWebAppRunFromZipProvider.ts
  Tasks/AzureFunctionDeploymentV1/deploymentProvider/WindowsWebAppWarDeployProvider.ts
  Tasks/AzureFunctionDeploymentV1/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureFunctionOnContainerDeploymentV1/Tests/AzureRmWebAppDeploymentProviderL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppRunFromZipProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppWarDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppWebDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/AzureWebAppDeploymentV1/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureWebAppDeploymentV1/deploymentProvider/WindowsWebAppRunFromZipProvider.ts
  Tasks/AzureWebAppDeploymentV1/deploymentProvider/WindowsWebAppWarDeployProvider.ts
  Tasks/AzureWebAppDeploymentV1/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureWebAppOnContainerDeploymentV1/Tests/AzureRmWebAppDeploymentProviderL0Tests.ts
Labels: Area: AzureAppService, Area: Release

#8993 Prefix package sources with feed- when writing packageSourceCredentials in nuget.config
  Tasks/Common/packaging-common/nuget/NuGetConfigHelper2.ts
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
  Tasks/NuGetCommandV2/task.json
  Tasks/NuGetCommandV2/task.loc.json
Labels: Area: Packaging

#8721 Enable dotnet core installer to work for any architecture
  Tasks/DotNetCoreInstallerV0/Tests/InstallWindows.ts
  Tasks/DotNetCoreInstallerV0/dotnetcoreinstaller.ts
  Tasks/DotNetCoreInstallerV0/externals/get-os-distro.sh
  Tasks/DotNetCoreInstallerV0/externals/get-os-platform.ps1
  Tasks/DotNetCoreInstallerV0/task.json
  Tasks/DotNetCoreInstallerV0/task.loc.json
Labels: Area: Release

#8992 Prefix package sources with feed- when writing packageSourceCredentials in nuget.config
  Tasks/Common/packaging-common/nuget/NuGetConfigHelper2.ts
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
  Tasks/NuGetCommandV2/task.json
  Tasks/NuGetCommandV2/task.loc.json
Labels: Area: Packaging

#8999 Prefix package sources with feed- when writing packageSourceCredentials in nuget.config
  Tasks/Common/packaging-common/nuget/NuGetConfigHelper2.ts
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
  Tasks/NuGetCommandV2/task.json
  Tasks/NuGetCommandV2/task.loc.json
Labels: Area: Packaging

#9043 Microsoft/users/pspill/packaging more provenance data
  Tasks/Common/packaging-common/provenance.ts
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
  Tasks/NpmV1/task.json
  Tasks/NpmV1/task.loc.json
  Tasks/NuGetCommandV2/task.json
  Tasks/NuGetCommandV2/task.loc.json
  Tasks/TwineAuthenticateV0/task.json
  Tasks/TwineAuthenticateV0/task.loc.json
  Tasks/UniversalPackagesV0/task.json
  Tasks/UniversalPackagesV0/task.loc.json
Labels: Area: Packaging

#9044 Microsoft/users/pspill/packaging more provenance data m144
  Tasks/Common/packaging-common/provenance.ts
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
  Tasks/NpmV1/task.json
  Tasks/NpmV1/task.loc.json
  Tasks/NuGetCommandV2/task.json
  Tasks/NuGetCommandV2/task.loc.json
  Tasks/TwineAuthenticateV0/task.json
  Tasks/TwineAuthenticateV0/task.loc.json
  Tasks/UniversalPackagesV0/task.json
  Tasks/UniversalPackagesV0/task.loc.json
Labels: Area: Packaging

#9050 Fixing indentation issue in readme file
  Tasks/GithubReleaseV0/README.md
Labels: Area: Release

#9054 AzCLI config directory for per release
  Tasks/AzureCLIV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureCLIV1/azureclitask.ts
  Tasks/AzureCLIV1/task.json
  Tasks/AzureCLIV1/task.loc.json
Labels: Area: Release

#9055 AzCLI config directory for per release M144
  Tasks/AzureCLIV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureCLIV1/azureclitask.ts
  Tasks/AzureCLIV1/task.json
  Tasks/AzureCLIV1/task.loc.json
Labels: Area: Release

#9059 AzCli task reset to m142 for RC2
  Tasks/AzureCLIV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureCLIV1/azureclitask.ts
  Tasks/AzureCLIV1/task.json
  Tasks/AzureCLIV1/task.loc.json
Labels: Area: Release

#8722 Added input to specify the name of the resource group deployment to create
  Tasks/AzureResourceGroupDeploymentV2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureResourceGroupDeploymentV2/models/DeployAzureRG.ts
  Tasks/AzureResourceGroupDeploymentV2/operations/ResourceGroup.ts
  Tasks/AzureResourceGroupDeploymentV2/task.json
  Tasks/AzureResourceGroupDeploymentV2/task.loc.json
Labels: Area: Release

#9068 Adding telemetry points for the GitHub release task
  Tasks/GitHubReleaseV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/GitHubReleaseV0/main.ts
  Tasks/GitHubReleaseV0/operations/Helper.ts
  Tasks/GitHubReleaseV0/operations/Utility.ts
  Tasks/GitHubReleaseV0/task.json
  Tasks/GitHubReleaseV0/task.loc.json
Labels: Area: Release

#9061 renaming folder name to match with make-options json
  Tasks/GitHubReleaseV0/README.md
  Tasks/GitHubReleaseV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/GitHubReleaseV0/ThirdPartyNotices.txt
  Tasks/GitHubReleaseV0/icon.png
  Tasks/GitHubReleaseV0/main.ts
  Tasks/GitHubReleaseV0/make.json
  Tasks/GitHubReleaseV0/operations/Action.ts
  Tasks/GitHubReleaseV0/operations/ChangeLog.ts
  Tasks/GitHubReleaseV0/operations/Helper.ts
  Tasks/GitHubReleaseV0/operations/Release.ts
  Tasks/GitHubReleaseV0/operations/Utility.ts
  Tasks/GitHubReleaseV0/operations/webClient.ts
  Tasks/GitHubReleaseV0/package-lock.json
  Tasks/GitHubReleaseV0/package.json
  Tasks/GitHubReleaseV0/task.json
  Tasks/GitHubReleaseV0/task.loc.json
  Tasks/GitHubReleaseV0/tsconfig.json
Labels: Area: Release

#9015 Port: Enable dotnet core installer to work for any architecture (#8721)
  Tasks/DotNetCoreInstallerV0/Tests/InstallWindows.ts
  Tasks/DotNetCoreInstallerV0/dotnetcoreinstaller.ts
  Tasks/DotNetCoreInstallerV0/externals/get-os-distro.sh
  Tasks/DotNetCoreInstallerV0/externals/get-os-platform.ps1
  Tasks/DotNetCoreInstallerV0/task.json
  Tasks/DotNetCoreInstallerV0/task.loc.json
Labels: Area: Release

#8919 [Kubernetes] Adding support to use inline configuration
  Tasks/KubernetesV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/KubernetesV1/Tests/L0.ts
  Tasks/KubernetesV1/Tests/TestSetup.ts
  Tasks/KubernetesV1/Tests/TestShared.ts
  Tasks/KubernetesV1/src/kubernetescommand.ts
  Tasks/KubernetesV1/src/utilities.ts
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
Labels: Area: Release

#9041 Users/suaggar/filetransformxdt
  Tasks/AzureRmWebAppDeploymentV3/operations/ContainerBasedDeploymentUtility.ts
  Tasks/AzureRmWebAppDeploymentV3/operations/FileTransformsUtility.ts
  Tasks/AzureRmWebAppDeploymentV3/operations/ParameterParserUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/L0ParameterParserUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/AzureRmWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/ContainerWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppRunFromZipProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppWebDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/ContainerBasedDeploymentUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/FileTransformsUtility.ts
  Tasks/Common/webdeployment-common/ParameterParserUtility.ts
  Tasks/Common/webdeployment-common/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/webdeployment-common/fileTransformationsUtility.ts
  Tasks/Common/webdeployment-common/module.json
  Tasks/Common/webdeployment-common/xdttransformationutility.ts
  Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts
  Tasks/FileTransformV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/FileTransformV1/filetransform.ts
  Tasks/FileTransformV1/task.json
  Tasks/FileTransformV1/task.loc.json
Labels: Area: Release

#9156 Users/suaggar/filetransformxdt
  Tasks/AzureRmWebAppDeploymentV3/operations/ContainerBasedDeploymentUtility.ts
  Tasks/AzureRmWebAppDeploymentV3/operations/FileTransformsUtility.ts
  Tasks/AzureRmWebAppDeploymentV3/operations/ParameterParserUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/L0ParameterParserUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/AzureRmWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/ContainerWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppRunFromZipProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppWebDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/ContainerBasedDeploymentUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/FileTransformsUtility.ts
  Tasks/Common/webdeployment-common/ParameterParserUtility.ts
  Tasks/Common/webdeployment-common/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/webdeployment-common/fileTransformationsUtility.ts
  Tasks/Common/webdeployment-common/module.json
  Tasks/Common/webdeployment-common/xdttransformationutility.ts
  Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts
  Tasks/FileTransformV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/FileTransformV1/filetransform.ts
  Tasks/FileTransformV1/task.json
  Tasks/FileTransformV1/task.loc.json
Labels: Area: AzureAppService, Area: Release

#9131 Adding L0 tests for GitHub release task
  Tasks/GitHubReleaseV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/GitHubReleaseV0/Tests/ActionL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/ActionTests.ts
  Tasks/GitHubReleaseV0/Tests/ChangeLogL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/ChangeLogTests.ts
  Tasks/GitHubReleaseV0/Tests/CreateAction2L0Tests.ts
  Tasks/GitHubReleaseV0/Tests/CreateActionL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/DeleteAction2L0Tests.ts
  Tasks/GitHubReleaseV0/Tests/DeleteActionL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/EditAction2L0Tests.ts
  Tasks/GitHubReleaseV0/Tests/EditActionL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/HelperL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/HelperTests.ts
  Tasks/GitHubReleaseV0/Tests/InvalidActionL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/L0.ts
  Tasks/GitHubReleaseV0/Tests/TestStrings.ts
  Tasks/GitHubReleaseV0/Tests/UtilityL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/package-lock.json
  Tasks/GitHubReleaseV0/Tests/package.json
  Tasks/GitHubReleaseV0/main.ts
  Tasks/GitHubReleaseV0/operations/Action.ts
  Tasks/GitHubReleaseV0/operations/ChangeLog.ts
  Tasks/GitHubReleaseV0/operations/Constants.ts
  Tasks/GitHubReleaseV0/operations/Helper.ts
  Tasks/GitHubReleaseV0/operations/Release.ts
  Tasks/GitHubReleaseV0/operations/Utility.ts
  Tasks/GitHubReleaseV0/task.json
  Tasks/GitHubReleaseV0/task.loc.json
Labels: Area: Release

#9032 task definition for "docker cli installer"
  Tasks/Common/utility-common/package-lock.json
  Tasks/DockerInstallerV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerInstallerV0/ThirdPartyNotices.txt
  Tasks/DockerInstallerV0/icon.png
  Tasks/DockerInstallerV0/make.json
  Tasks/DockerInstallerV0/package-lock.json
  Tasks/DockerInstallerV0/package.json
  Tasks/DockerInstallerV0/src/dockertoolinstaller.ts
  Tasks/DockerInstallerV0/src/utils.ts
  Tasks/DockerInstallerV0/task.json
  Tasks/DockerInstallerV0/task.loc.json
  Tasks/DockerInstallerV0/tsconfig.json
Labels: Area: Release

#9181 bumped AFC patches
  Tasks/AzureFileCopyV1/task.json
  Tasks/AzureFileCopyV1/task.loc.json
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
Labels: Area: Release

#9194 add codeowner for DownloadGitHubReleases task
  .github/CODEOWNERS
Labels: Area: Release

#9206 Users/suaggar/newtask text change
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/FileTransformV1/task.json
  Tasks/FileTransformV1/task.loc.json
Labels: Area: AzureAppService, Area: Release
