Repository microsoft/azure-pipelines-tasks, pull requests merged in 2018-04, with the labels that each got.

#6835 changes to support TLS 1.2 in powershell based tasks
  Tasks/AzureCloudPowerShellDeployment/make.json
  Tasks/AzureCloudPowerShellDeployment/task.json
  Tasks/AzureCloudPowerShellDeployment/task.loc.json
  Tasks/AzureFileCopy/make.json
  Tasks/AzureFileCopy/task.json
  Tasks/AzureFileCopy/task.loc.json
  Tasks/AzurePowerShell/make.json
  Tasks/AzurePowerShell/task.json
  Tasks/AzurePowerShell/task.loc.json
  Tasks/Common/TlsHelper_/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/TlsHelper_/TlsHelper_.psm1
  Tasks/Common/TlsHelper_/module.json
  Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.AzurePreferredFallsBack.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.AzureRMPreferredFallsBack.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.BothPreferredFallsBack.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.ThrowsWhenNotFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.ValidatesClassicVersion.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ImportsModules.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ReturnsFalseWhenNotFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ValidatesRMProfileFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromSdkPath.ImportsModule.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromSdkPath.ReturnsFalseWhenNotFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-Azure.PassesInputs.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-Azure.ThrowsWhenServiceNameIsNull.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenAzureStackSPAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenCertAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenCertAuthAndEnvironment.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenSPAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenUPAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsUsefulErrorWhenSPAuthAndAddAccountFails.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsUsefulErrorWhenUPAuthAndAddAccountFails.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsWhenRMAndCertAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsWhenSPAuthAndClassic099.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsWhenUnsupportedAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/OverriddesGlobalDebugPreference.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Set-CurrentAzureRMSubscription.PassesValues.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Set-CurrentAzureSubscription.PassesValues.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Set-UserAgent.PassesValues.ps1
  Tasks/Common/VstsAzureHelpers_/VstsAzureHelpers_.psm1
  Tasks/Common/VstsAzureRestHelpers_/Tests/Get-AzureActiveDirectoryResourceId.ps1
  Tasks/Common/VstsAzureRestHelpers_/Tests/Populate-AzureStackDependencyData.ps1
  Tasks/Common/VstsAzureRestHelpers_/VstsAzureRestHelpers_.psm1
  Tasks/SqlAzureDacpacDeployment/make.json
  Tasks/SqlAzureDacpacDeployment/task.json
  Tasks/SqlAzureDacpacDeployment/task.loc.json
Labels: Area: Release

#6870 readd preview version for App Service Deploy task
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: AzureAppService, Area: Release

#6889 [PowerShellOnTargetMachines] Remove DTL Sdk Telemetry
  Tasks/PowerShellOnTargetMachines/PowerShellOnTargetMachines.ps1
  Tasks/PowerShellOnTargetMachines/task.json
  Tasks/PowerShellOnTargetMachines/task.loc.json
Labels: Area: Release

#6884 Update README.md
  Tasks/AzureRmWebAppDeployment/README.md
Labels: Area: Release

#6823 Users/rok/telemtry in m123 for older version
  Tasks/PowerShellOnTargetMachines/PowerShellJob.ps1
  Tasks/PowerShellOnTargetMachines/PowerShellOnTargetMachines.ps1
  Tasks/PowerShellOnTargetMachines/task.json
  Tasks/PowerShellOnTargetMachines/task.loc.json
  Tasks/WindowsMachineFileCopy/task.json
  Tasks/WindowsMachineFileCopy/task.loc.json
Labels: Area: Release

#6863 remove usage of net exe
  Tasks/WindowsMachineFileCopy/RoboCopyJob.ps1
  Tasks/WindowsMachineFileCopy/Strings/resources.resjson/en-US/resources.resjson
  Tasks/WindowsMachineFileCopy/task.json
  Tasks/WindowsMachineFileCopy/task.loc.json
Labels: Area: Release

#6933 [PowerShellOnTargetMachines] Remove DTL Sdk Telemetry - on - releases - m133 (#6889)
  Tasks/PowerShellOnTargetMachines/PowerShellOnTargetMachines.ps1
  Tasks/PowerShellOnTargetMachines/task.json
  Tasks/PowerShellOnTargetMachines/task.loc.json
Labels: Area: Release

#6920 Add provisioningProfileName input alongside provisioningProfileUuid.
  Tasks/Common/ios-signing-common/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/ios-signing-common/ios-signing-common.ts
  Tasks/Common/ios-signing-common/module.json
  Tasks/Common/securefiles-common/package-lock.json
  Tasks/Common/securefiles-common/package.json
  Tasks/Common/securefiles-common/securefiles-common.ts
  Tasks/InstallAppleCertificate/package-lock.json
  Tasks/InstallAppleProvisioningProfile/Tests/L0SecureFile.ts
  Tasks/InstallAppleProvisioningProfile/Tests/L0SourceRepository.ts
  Tasks/InstallAppleProvisioningProfile/installprovprofile.ts
  Tasks/InstallAppleProvisioningProfile/package-lock.json
  Tasks/InstallAppleProvisioningProfile/preinstallprovprofile.ts
  Tasks/InstallAppleProvisioningProfile/task.json
  Tasks/InstallAppleProvisioningProfile/task.loc.json
  Tasks/Xcode/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Xcode/Tests/L0.ts
  Tasks/Xcode/Tests/L0CreateIpaWithCodeSigningIdentifiers.ts
  Tasks/Xcode/package-lock.json
  Tasks/Xcode/task.json
  Tasks/Xcode/task.loc.json
  Tasks/Xcode/xcode.ts
  Tests-Legacy/L0/Xcode/_suite.ts
  Tests-Legacy/L0/Xcode/responseSigningFile.json
  Tests-Legacy/L0/Xcode/responseSigningId.json
  definitions/ios-signing-common.d.ts
Labels: Area: CrossPlatform, Area: Mobile

#6956 Stop writing temp files in the Xcode tests.
  Tasks/Common/ios-signing-common/ios-signing-common.ts
  Tasks/InstallAppleCertificate/Tests/L0DeleteTempKeychain.ts
  Tasks/InstallAppleCertificate/Tests/L0InstallCertWithEmptyPassword.ts
  Tasks/InstallAppleCertificate/Tests/L0InstallDefaultKeychain.ts
  Tasks/InstallAppleCertificate/Tests/L0InstallTempKeychain.ts
  Tasks/InstallAppleCertificate/Tests/L0UserSupplyCN.ts
  Tasks/InstallAppleCertificate/task.json
  Tasks/InstallAppleCertificate/task.loc.json
  Tasks/InstallAppleProvisioningProfile/Tests/L0RemoveProfile.ts
  Tasks/InstallAppleProvisioningProfile/task.json
  Tasks/InstallAppleProvisioningProfile/task.loc.json
Labels: Area: CrossPlatform, Area: Mobile

#6802 1. add support for initialization script and session variables
  Tasks/PowerShellOnTargetMachines2/JobHelper.ps1
  Tasks/PowerShellOnTargetMachines2/PowerShellOnTargetMachines.ps1
  Tasks/PowerShellOnTargetMachines2/RunPowerShellScriptJob.ps1
  Tasks/PowerShellOnTargetMachines2/SessionHelper.ps1
  Tasks/PowerShellOnTargetMachines2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/PowerShellOnTargetMachines2/Utility.ps1
  Tasks/PowerShellOnTargetMachines2/task.json
  Tasks/PowerShellOnTargetMachines2/task.loc.json
Labels: Area: Release

#6654 powershell rest msi changes
  Tasks/Common/VstsAzureRestHelpers_/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/VstsAzureRestHelpers_/Tests/Get-AzureRMAccessToken.ps1
  Tasks/Common/VstsAzureRestHelpers_/Tests/L0.ts
  Tasks/Common/VstsAzureRestHelpers_/VstsAzureRestHelpers_.psm1
  Tasks/Common/VstsAzureRestHelpers_/module.json
Labels: Area: Release

#6655 msi for native support
  Tasks/AzurePowerShell/Utility.ps1
  Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1
  Tasks/Common/VstsAzureHelpers_/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ManagedServiceIdentity.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/L0.ts
  Tasks/Common/VstsAzureHelpers_/VstsAzureHelpers_.psm1
  Tasks/Common/VstsAzureHelpers_/module.json
Labels: Area: Release

#6969 support for check latest Helm version
  Tasks/Common/utility-common/downloadutility.ts
  Tasks/Common/utility-common/kubectlutility.ts
  Tasks/HelmInstaller/Strings/resources.resjson/en-US/resources.resjson
  Tasks/HelmInstaller/src/helminstaller.ts
  Tasks/HelmInstaller/task.json
  Tasks/HelmInstaller/task.loc.json
  Tasks/Kubernetes/npm-shrinkwrap.json
  Tasks/Kubernetes/src/utilities.ts
  Tasks/Kubernetes/task.json
  Tasks/Kubernetes/task.loc.json
Labels: Area: Release

#6964 Adding support to override parameters in serviceFabricDeploy Task.
  Tasks/ServiceFabricDeploy/Create-DiffPackage.psm1
  Tasks/ServiceFabricDeploy/Strings/resources.resjson/en-US/resources.resjson
  Tasks/ServiceFabricDeploy/Tests/AadDeploy.ps1
  Tasks/ServiceFabricDeploy/Tests/CertDeploy.ps1
  Tasks/ServiceFabricDeploy/Tests/CertDeployWithDocker.ps1
  Tasks/ServiceFabricDeploy/Tests/CertDeployWithDockerMultiThumbprint.ps1
  Tasks/ServiceFabricDeploy/Tests/CreateDiffPkg.ps1
  Tasks/ServiceFabricDeploy/Tests/NoAuthDeploy.ps1
  Tasks/ServiceFabricDeploy/Tests/WindowsAuthDeploy.ps1
  Tasks/ServiceFabricDeploy/deploy.ps1
  Tasks/ServiceFabricDeploy/task.json
  Tasks/ServiceFabricDeploy/task.loc.json
  Tasks/ServiceFabricDeploy/utilities.ps1
Labels: Area: Release, Area: ServiceFabric

#6978 output variable support in azure app service manage task
  Tasks/AzureAppServiceManage/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureAppServiceManage/operations/KuduServiceUtils.ts
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
Labels: Area: Release

#6848 Webapp Deployment by Publish Profile file and Code Refactoring
  Tasks/AzureRmWebAppDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/AzureRmWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/ContainerWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/DeploymentFactory.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/IWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/PublishProfileWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/WindowsWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeployment/operations/Constants.ts
  Tasks/AzureRmWebAppDeployment/operations/PublishProfileUtility.ts
  Tasks/AzureRmWebAppDeployment/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeployment/operations/parameterparser.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/webdeployment-common/npm-shrinkwrap.json
Labels: Area: AzureAppService, Area: Release

#6980 XML Var. substitution - Escape XML characters
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/webdeployment-common/Tests/L1XmlVarSub/Web.config
  Tasks/Common/webdeployment-common/Tests/L1XmlVarSub/Web_Expected.config
  Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts
  Tasks/IISWebAppDeploymentOnMachineGroup/task.json
  Tasks/IISWebAppDeploymentOnMachineGroup/task.loc.json
Labels: Area: AzureAppService, Area: Release

#7048 Python extension path fix - Azure App Service Manage Task m132
  Tasks/AzureAppServiceManage/operations/KuduServiceUtils.ts
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
Labels: Area: AzureAppService, Area: Release

#7034 Resource string - App Service Post-deployment script timeout
  Tasks/AzureRmWebAppDeployment/operations/KuduServiceUtility.ts
Labels: Area: AzureAppService, Area: Release

#7026 Webapp Deployment by Publish Profile file and Code Refactoring Users/vimimrot/publish profile m133
  Tasks/AzureRmWebAppDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/AzureRmWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/ContainerWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/DeploymentFactory.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/IWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/PublishProfileWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/WindowsWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeployment/operations/Constants.ts
  Tasks/AzureRmWebAppDeployment/operations/PublishProfileUtility.ts
  Tasks/AzureRmWebAppDeployment/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeployment/operations/parameterparser.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/webdeployment-common/npm-shrinkwrap.json
Labels: Area: AzureAppService, Area: Release

#6906 Add support for TLS1.2 in SF tasks
  Tasks/Common/ServiceFabricHelpers/Connect-ServiceFabricClusterFromServiceEndpoint.ps1
  Tasks/ServiceFabricComposeDeploy/make.json
  Tasks/ServiceFabricComposeDeploy/task.json
  Tasks/ServiceFabricComposeDeploy/task.loc.json
  Tasks/ServiceFabricDeploy/Tests/AadDeploy.ps1
  Tasks/ServiceFabricDeploy/Tests/CertDeploy.ps1
  Tasks/ServiceFabricDeploy/Tests/CertDeployWithDocker.ps1
  Tasks/ServiceFabricDeploy/Tests/CertDeployWithDockerMultiThumbprint.ps1
  Tasks/ServiceFabricDeploy/Tests/CreateDiffPkg.ps1
  Tasks/ServiceFabricDeploy/Tests/NoAuthDeploy.ps1
  Tasks/ServiceFabricDeploy/Tests/WindowsAuthDeploy.ps1
  Tasks/ServiceFabricDeploy/make.json
  Tasks/ServiceFabricDeploy/task.json
  Tasks/ServiceFabricDeploy/task.loc.json
  Tasks/ServiceFabricPowerShell/Tests/SetupMocks.ps1
  Tasks/ServiceFabricPowerShell/make.json
  Tasks/ServiceFabricPowerShell/task.json
  Tasks/ServiceFabricPowerShell/task.loc.json
Labels: Area: Release

#7095 Case sensitive file name bug fix
  Tasks/AzureRmWebAppDeployment/deploymentProvider/PublishProfileWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: AzureAppService, Area: Release

#7096 Case sensitive file name bug fix
  Tasks/AzureRmWebAppDeployment/deploymentProvider/PublishProfileWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: AzureAppService, Area: Release

#7102 handle special characters in app name - App Service Tasks
  Tasks/AzureAppServiceManage/Tests/L0.ts
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
  Tasks/AzureRmWebAppDeployment/Tests/L0.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/azure-arm-rest/Tests/L0-azure-arm-resource-tests.ts
  Tasks/Common/azure-arm-rest/Tests/azure-arm-resource-tests.ts
  Tasks/Common/azure-arm-rest/Tests/mock_utils.ts
  Tasks/Common/azure-arm-rest/azure-arm-resource.ts
Labels: Area: AzureAppService, Area: Release

#6209 Format commands and code properly
  Tasks/AzureKeyVault/README.md
Labels: Area: Release
