Repository microsoft/azure-pipelines-tasks, pull requests merged in 2018-05, with the labels that each got.

#7103 Handle special characters in App Name - App Service Tasks M134
  Tasks/AzureAppServiceManage/Tests/L0.ts
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
  Tasks/AzureRmWebAppDeployment/Tests/L0.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/azure-arm-rest/Tests/L0-azure-arm-resource-tests.ts
  Tasks/Common/azure-arm-rest/Tests/azure-arm-resource-tests.ts
  Tasks/Common/azure-arm-rest/Tests/mock_utils.ts
  Tasks/Common/azure-arm-rest/azure-arm-resource.ts
Labels: Area: AzureAppService, Area: Release

#7071 Users/suaggar/dynamic extension list
  Tasks/AzureAppServiceManage/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureAppServiceManage/operations/KuduServiceUtils.ts
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
  Tasks/Common/azure-arm-rest/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/azure-arm-rest/Tests/L0-azure-arm-app-service-kudu-tests.ts
  Tasks/Common/azure-arm-rest/Tests/azure-arm-app-service-kudu-tests.ts
  Tasks/Common/azure-arm-rest/Tests/mock_utils.ts
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/azure-arm-rest/module.json
Labels: Area: AzureAppService, Area: Release

#7107 adding error codes in retry logic
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
  Tasks/Common/azure-arm-rest/Tests/L0-azure-arm-app-service.ts
  Tasks/Common/azure-arm-rest/Tests/mock_utils.ts
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/azure-arm-rest/webClient.ts
Labels: Area: AzureAppService, Area: Release

#6789 Users/arjgupta/ps on target machine
  Tasks/Common/RemoteDeployer/JobHelper.ps1
  Tasks/Common/RemoteDeployer/RemoteDeployer.Utility.ps1
  Tasks/Common/RemoteDeployer/RemoteDeployer.psm1
  Tasks/Common/RemoteDeployer/RunPowerShellScriptJob.ps1
  Tasks/Common/RemoteDeployer/SessionHelper.ps1
  Tasks/Common/RemoteDeployer/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/RemoteDeployer/Tests/Get-TargetMachines.UsesCorrectPortForTargetMachine.ps1
  Tasks/Common/RemoteDeployer/Tests/Get-WinRmConnectionToTargetMachine.ThrowsIfUnableToCreateSession.ps1
  Tasks/Common/RemoteDeployer/Tests/L0.ts
  Tasks/Common/RemoteDeployer/Tests/Retry-Connection.AttemptsConnectionOnSpecificCondition.ps1
  Tasks/Common/RemoteDeployer/Tests/Retry-Connection.AttemptsConnectionStateDisconnectedAvailabilityNone.ps1
  Tasks/Common/RemoteDeployer/Tests/Retry-Connection.DoesNotThrowIfCannotGetSession.ps1
  Tasks/Common/RemoteDeployer/Tests/Retry-Connection.DoesNotThrowIfReceiveSessionThrows.ps1
  Tasks/Common/RemoteDeployer/module.json
  Tasks/Common/RemoteDeployer/tsconfig.json
  Tasks/PowerShellOnTargetMachinesV3/PowerShellOnTargetMachines.ps1
  Tasks/PowerShellOnTargetMachinesV3/README.md
  Tasks/PowerShellOnTargetMachinesV3/Strings/resources.resjson/en-US/resources.resjson
  Tasks/PowerShellOnTargetMachinesV3/Utility.ps1
  Tasks/PowerShellOnTargetMachinesV3/icon.png
  Tasks/PowerShellOnTargetMachinesV3/icon.svg
  Tasks/PowerShellOnTargetMachinesV3/make.json
  Tasks/PowerShellOnTargetMachinesV3/task.json
  Tasks/PowerShellOnTargetMachinesV3/task.loc.json
  make-options.json
Labels: Area: Release

#7115 Minor Go string tweaks based on team feedback
  Tasks/Go/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Go/task.json
  Tasks/Go/task.loc.json
  Tasks/GoTool/Strings/resources.resjson/en-US/resources.resjson
  Tasks/GoTool/task.json
  Tasks/GoTool/task.loc.json
Labels: Area: Release

#6938 Updated the validation for cloud service after deployment to wait for…
  Tasks/AzureCloudPowerShellDeployment/Publish-AzureCloudDeployment.ps1
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Utility.ps1
  Tasks/AzureCloudPowerShellDeployment/task.json
  Tasks/AzureCloudPowerShellDeployment/task.loc.json
Labels: Area: Release

#7199 Azure App Service Deploy - on demand Rename Locked files & Warm-up slot
  Tasks/AzureAppServiceManage/operations/KuduServiceUtils.ts
  Tasks/AzureRmWebAppDeployment/Tests/L0.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/AzureRmWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/WindowsWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeployment/operations/KuduServiceUtility.ts
  Tasks/AzureRmWebAppDeployment/operations/WebDeployUtility.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/webdeployment-common/Tests/L0MSDeployUtility.ts
  Tasks/Common/webdeployment-common/deployusingmsdeploy.ts
  Tasks/Common/webdeployment-common/msdeployutility.ts
  Tasks/Common/webdeployment-common/packageUtility.ts
Labels: Area: AzureAppService, Area: Release

#7222 fixed single file blob upload
  Tasks/AzureFileCopyV2/AzureFileCopyRemoteJob.ps1
  Tasks/AzureFileCopyV2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFileCopyV2/Tests/L0UploadFilesToAzureContainer.ps1
  Tasks/AzureFileCopyV2/Utility.ps1
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
Labels: Area: Release

#7226 Multiple fixes to the CLT tasks (QuickPerfTestV1|RunLoadTestV1|RunJMeterLoadTestV1)
  Tasks/QuickPerfTestV1/CltTasksUtility.ps1
  Tasks/QuickPerfTestV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/QuickPerfTestV1/task.json
  Tasks/QuickPerfTestV1/task.loc.json
  Tasks/RunJMeterLoadTestV1/CltTasksUtility.ps1
  Tasks/RunJMeterLoadTestV1/Start-ApacheJMeterTest.ps1
  Tasks/RunJMeterLoadTestV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/RunJMeterLoadTestV1/task.json
  Tasks/RunJMeterLoadTestV1/task.loc.json
  Tasks/RunLoadTestV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/RunLoadTestV1/task.json
  Tasks/RunLoadTestV1/task.loc.json
Labels: Area: Test

#7251 Multiple fixes to the CLT tasks (QuickPerfTestV1|RunLoadTestV1|RunJMeterLoadTestV1)
  Tasks/QuickPerfTestV1/CltTasksUtility.ps1
  Tasks/QuickPerfTestV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/QuickPerfTestV1/task.json
  Tasks/QuickPerfTestV1/task.loc.json
  Tasks/RunJMeterLoadTestV1/CltTasksUtility.ps1
  Tasks/RunJMeterLoadTestV1/Start-ApacheJMeterTest.ps1
  Tasks/RunJMeterLoadTestV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/RunJMeterLoadTestV1/task.json
  Tasks/RunJMeterLoadTestV1/task.loc.json
  Tasks/RunLoadTestV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/RunLoadTestV1/task.json
  Tasks/RunLoadTestV1/task.loc.json
Labels: Area: Test

#7202 azure file copy task hotfix
  Tasks/AzureFileCopyV1/AzureUtilityGTE1.0.ps1
  Tasks/AzureFileCopyV1/task.json
  Tasks/AzureFileCopyV1/task.loc.json
  Tasks/AzureFileCopyV2/AzureUtilityGTE1.0.ps1
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
  Tasks/Common/VstsAzureHelpers_/VstsAzureHelpers_.psm1
Labels: Area: Release

#7261 chef and chef url update
  Tasks/ChefKnifeV1/task.json
  Tasks/ChefKnifeV1/task.loc.json
  Tasks/ChefV1/task.json
  Tasks/ChefV1/task.loc.json
  Tasks/IISWebAppManagementOnMachineGroupV0/task.json
  Tasks/IISWebAppManagementOnMachineGroupV0/task.loc.json
Labels: Area: Release

#7218 Zip Deploy support for web apps
  Tasks/AzureRmWebAppDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/DeploymentFactory.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/WindowsWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/WindowsWebAppWebDeployProvider.ts
  Tasks/AzureRmWebAppDeployment/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureRmWebAppDeployment/operations/KuduServiceUtility.ts
  Tasks/AzureRmWebAppDeployment/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeployment/operations/WebDeployUtility.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: AzureAppService, Area: Release

#7106 added taskinstancename property in servicebus server task
  Tasks/PublishToAzureServiceBusV1/task.json
  Tasks/PublishToAzureServiceBusV1/task.loc.json
Labels: Area: Release

#7300 Major version change kubernetes
  Tasks/Common/docker-common/registryauthenticationprovider/acrauthenticationtokenprovider.ts
  Tasks/KubernetesV1/Strings/resources.resjson/de-de/resources.resjson
  Tasks/KubernetesV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/KubernetesV1/Strings/resources.resjson/es-es/resources.resjson
  Tasks/KubernetesV1/Strings/resources.resjson/fr-fr/resources.resjson
  Tasks/KubernetesV1/Strings/resources.resjson/it-IT/resources.resjson
  Tasks/KubernetesV1/Strings/resources.resjson/ja-jp/resources.resjson
  Tasks/KubernetesV1/Strings/resources.resjson/ko-KR/resources.resjson
  Tasks/KubernetesV1/Strings/resources.resjson/ru-RU/resources.resjson
  Tasks/KubernetesV1/Strings/resources.resjson/zh-CN/resources.resjson
  Tasks/KubernetesV1/Strings/resources.resjson/zh-TW/resources.resjson
  Tasks/KubernetesV1/Tests/L0.ts
  Tasks/KubernetesV1/Tests/TestSetup.ts
  Tasks/KubernetesV1/Tests/TestShared.ts
  Tasks/KubernetesV1/Tests/package.json
  Tasks/KubernetesV1/ThirdPartyNotices.txt
  Tasks/KubernetesV1/icon.png
  Tasks/KubernetesV1/make.json
  Tasks/KubernetesV1/npm-shrinkwrap.json
  Tasks/KubernetesV1/package.json
  Tasks/KubernetesV1/src/clusterconnection.ts
  Tasks/KubernetesV1/src/clusters/armkubernetescluster.ts
  Tasks/KubernetesV1/src/clusters/generickubernetescluster.ts
  Tasks/KubernetesV1/src/kubernetes.ts
  Tasks/KubernetesV1/src/kubernetescommand.ts
  Tasks/KubernetesV1/src/kubernetesconfigmap.ts
  Tasks/KubernetesV1/src/kubernetessecret.ts
  Tasks/KubernetesV1/src/utilities.ts
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
  Tasks/KubernetesV1/tsconfig.json
  Tasks/KubernetesV1/typings/assertion-error/assertion-error.d.ts
  Tasks/KubernetesV1/typings/chai/chai.d.ts
  Tasks/KubernetesV1/typings/del/del.d.ts
  Tasks/KubernetesV1/typings/glob/glob.d.ts
  Tasks/KubernetesV1/typings/js-yaml/js-yaml.d.ts
  Tasks/KubernetesV1/typings/minimatch/minimatch.d.ts
  Tasks/KubernetesV1/typings/mocha/mocha.d.ts
  Tasks/KubernetesV1/typings/node/node.d.ts
  Tasks/KubernetesV1/typings/q/index.d.ts
  Tasks/KubernetesV1/typings/q/typings.json
  Tasks/KubernetesV1/typings/shelljs/shelljs.d.ts
  Tasks/KubernetesV1/typings/sinon-chai/sinon-chai.d.ts
  Tasks/KubernetesV1/typings/sinon/sinon.d.ts
  Tasks/KubernetesV1/typings/tsd.d.ts
  make-options.json
Labels: Area: Release

#7306 Export dotnet root
  Tasks/DotNetCoreInstallerV0/dotnetcoreinstaller.ts
  Tasks/DotNetCoreInstallerV0/task.json
  Tasks/DotNetCoreInstallerV0/task.loc.json
Labels: Area: Release

#7322 ASE Recommendation message - App Service Tasks
  Tasks/AzureAppServiceManageV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureAppServiceManageV0/task.json
  Tasks/AzureAppServiceManageV0/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/azure-arm-rest/Tests/L0-azure-arm-app-service-kudu-tests.ts
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/azure-arm-rest/module.json
Labels: Area: AzureAppService, Area: Release

#7282 Simplification of Docker task
  Tasks/DockerV1/Strings/resources.resjson/de-de/resources.resjson
  Tasks/DockerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerV1/Strings/resources.resjson/es-es/resources.resjson
  Tasks/DockerV1/Strings/resources.resjson/fr-fr/resources.resjson
  Tasks/DockerV1/Strings/resources.resjson/it-IT/resources.resjson
  Tasks/DockerV1/Strings/resources.resjson/ja-jp/resources.resjson
  Tasks/DockerV1/Strings/resources.resjson/ko-KR/resources.resjson
  Tasks/DockerV1/Strings/resources.resjson/ru-RU/resources.resjson
  Tasks/DockerV1/Strings/resources.resjson/zh-CN/resources.resjson
  Tasks/DockerV1/Strings/resources.resjson/zh-TW/resources.resjson
  Tasks/DockerV1/Tests/L0.ts
  Tasks/DockerV1/Tests/TestSetup.ts
  Tasks/DockerV1/Tests/TestShared.ts
  Tasks/DockerV1/ThirdPartyNotices.txt
  Tasks/DockerV1/container.ts
  Tasks/DockerV1/containerbuild.ts
  Tasks/DockerV1/containercommand.ts
  Tasks/DockerV1/containerpush.ts
  Tasks/DockerV1/containerrun.ts
  Tasks/DockerV1/containertag.ts
  Tasks/DockerV1/icon.png
  Tasks/DockerV1/make.json
  Tasks/DockerV1/npm-shrinkwrap.json
  Tasks/DockerV1/package.json
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
  Tasks/DockerV1/tsconfig.json
  Tasks/DockerV1/typings/assertion-error/assertion-error.d.ts
  Tasks/DockerV1/typings/chai/chai.d.ts
  Tasks/DockerV1/typings/del/del.d.ts
  Tasks/DockerV1/typings/glob/glob.d.ts
  Tasks/DockerV1/typings/js-yaml/js-yaml.d.ts
  Tasks/DockerV1/typings/minimatch/minimatch.d.ts
  Tasks/DockerV1/typings/mocha/mocha.d.ts
  Tasks/DockerV1/typings/node/node.d.ts
  Tasks/DockerV1/typings/q/index.d.ts
  Tasks/DockerV1/typings/q/typings.json
  Tasks/DockerV1/typings/shelljs/shelljs.d.ts
  Tasks/DockerV1/typings/sinon-chai/sinon-chai.d.ts
  Tasks/DockerV1/typings/sinon/sinon.d.ts
  Tasks/DockerV1/typings/tsd.d.ts
  Tasks/DockerV1/utils.ts
  make-options.json
Labels: Area: Release
