Repository microsoft/azure-pipelines-tasks, pull requests merged in 2018-03, with the labels that each got.

#6522 Changes in package-lock file after building the task locally
  Tasks/AzureResourceGroupDeployment/package-lock.json
Labels: Area: Release

#6516 Changes in package-lock file of AzureRG after building the task locally
  Tasks/AzureResourceGroupDeployment/package-lock.json
Labels: Area: Release

#6380 don't try to copy code/config/data folder if it does not exist
  Tasks/ServiceFabricDeploy/Create-DiffPackage.psm1
  Tasks/ServiceFabricDeploy/Tests/CreateDiffPkg.ps1
  Tasks/ServiceFabricDeploy/Tests/data/DiffPkgAssets/AppPkg/Stateless4Pkg/ServiceManifest.xml
  Tasks/ServiceFabricDeploy/deploy.ps1
  Tasks/ServiceFabricDeploy/task.json
  Tasks/ServiceFabricDeploy/task.loc.json
Labels: Area: Release, Area: ServiceFabric

#6422 App Service Deploy 4.* Task Version (Preview)
  Tasks/AzureAppServiceManage/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
  Tasks/AzureRmWebAppDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeployment/operations/ContainerBasedDeploymentUtility.ts
  Tasks/AzureRmWebAppDeployment/operations/FileTransformsUtility.ts
  Tasks/AzureRmWebAppDeployment/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: AzureAppService, Area: Release

#6546 Users/aydey/tpn on releases
  Tasks/DotNetCoreInstaller/ThirdPartyNotices.txt
  Tasks/Go/ThirdPartyNotices.txt
  Tasks/GoTool/ThirdPartyNotices.txt
  Tasks/PyPIPublisher/ThirdPartyNotices.txt
Labels: Area: Release

#6578 Adding TPN for AzureRG task (#6575)
  Tasks/AzureResourceGroupDeployment/ThirdPartyNotices.txt
Labels: Area: Release

#6581 Users/chshrikh/azure ps module load fix m130
  Tasks/AzurePowerShell/AzurePowerShell.ps1
  Tasks/AzurePowerShell/Tests/PerformsBasicFlow.ps1
  Tasks/AzurePowerShell/Utility.ps1
  Tasks/AzurePowerShell/task.json
  Tasks/AzurePowerShell/task.loc.json
Labels: Area: Release

#6576 updated the logic to load the module as per auth scheme
  Tasks/AzurePowerShell/AzurePowerShell.ps1
  Tasks/AzurePowerShell/Tests/PerformsBasicFlow.ps1
  Tasks/AzurePowerShell/Utility.ps1
  Tasks/AzurePowerShell/task.json
  Tasks/AzurePowerShell/task.loc.json
Labels: Area: Release

#6604 Deprecate Tasks: Chef and ChefKnife
  Tasks/Chef/task.json
  Tasks/Chef/task.loc.json
  Tasks/ChefKnife/task.json
  Tasks/ChefKnife/task.loc.json
Labels: Area: Release

#6605 Deprecate Tasks: Chef and ChefKnife (#6604)
  Tasks/Chef/task.json
  Tasks/Chef/task.loc.json
  Tasks/ChefKnife/task.json
  Tasks/ChefKnife/task.loc.json
Labels: Area: Release

#6527 add default params for MSDEPLOY
  Tasks/AzureRmWebAppDeployment/Tests/L0.ts
  Tasks/AzureRmWebAppDeployment/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/webdeployment-common/Tests/L0MSDeployUtility.ts
  Tasks/Common/webdeployment-common/msdeployutility.ts
  Tasks/IISWebAppDeploymentOnMachineGroup/Tests/L0.ts
Labels: Area: AzureAppService, Area: Release

#6579 Users/hiyada/war deployment
  Tasks/AzureRmWebAppDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeployment/operations/WarDeploymentUtilities.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: AzureAppService, Area: Release

#6485 Telemetry data of unique vm for older version of power shell task
  Tasks/PowerShellOnTargetMachines/PowerShellJob.ps1
  Tasks/PowerShellOnTargetMachines/PowerShellOnTargetMachines.ps1
  Tasks/PowerShellOnTargetMachines/Utility.ps1
  Tasks/PowerShellOnTargetMachines/task.json
  Tasks/PowerShellOnTargetMachines/task.loc.json
Labels: Area: Release

#6607 Logging merging test result files message as debug instead of warning
  Tasks/PublishTestResults/Strings/resources.resjson/en-US/resources.resjson
  Tasks/PublishTestResults/publishtestresults.ts
  Tasks/PublishTestResults/task.json
  Tasks/PublishTestResults/task.loc.json
Labels: Area: Test

#6610 Users/hiyada/war deployment (#6579)
  Tasks/AzureRmWebAppDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeployment/operations/WarDeploymentUtilities.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: Release

#6257 create directory in share path support
  Tasks/WindowsMachineFileCopy/RoboCopyJob.ps1
  Tasks/WindowsMachineFileCopy/task.json
  Tasks/WindowsMachineFileCopy/task.loc.json
Labels: Area: Release

#6616 Update ThirdPartyNotices.txt
  Tasks/DownloadPackage/ThirdPartyNotices.txt
Labels: Area: Release

#6504 Helm task
  Tasks/Common/azure-arm-rest/AzureServiceClient.ts
  Tasks/Common/azure-arm-rest/azure-arm-aks-service.ts
  Tasks/Common/azure-arm-rest/azureModels.ts
  Tasks/HelmDeploy/Strings/resources.resjson/en-US/resources.resjson
  Tasks/HelmDeploy/icon.png
  Tasks/HelmDeploy/make.json
  Tasks/HelmDeploy/package-lock.json
  Tasks/HelmDeploy/package.json
  Tasks/HelmDeploy/src/basecommand.ts
  Tasks/HelmDeploy/src/helm.ts
  Tasks/HelmDeploy/src/helmcli.ts
  Tasks/HelmDeploy/src/kubernetescli.ts
  Tasks/HelmDeploy/src/utils.ts
  Tasks/HelmDeploy/task.json
  Tasks/HelmDeploy/task.loc.json
  Tasks/HelmDeploy/tsconfig.json
  Tasks/HelmDeploy/typings/assertion-error/assertion-error.d.ts
  Tasks/HelmDeploy/typings/chai/chai.d.ts
  Tasks/HelmDeploy/typings/del/del.d.ts
  Tasks/HelmDeploy/typings/glob/glob.d.ts
  Tasks/HelmDeploy/typings/js-yaml/js-yaml.d.ts
  Tasks/HelmDeploy/typings/minimatch/minimatch.d.ts
  Tasks/HelmDeploy/typings/mocha/mocha.d.ts
  Tasks/HelmDeploy/typings/node/node.d.ts
  Tasks/HelmDeploy/typings/q/index.d.ts
  Tasks/HelmDeploy/typings/q/typings.json
  Tasks/HelmDeploy/typings/shelljs/shelljs.d.ts
  Tasks/HelmDeploy/typings/sinon-chai/sinon-chai.d.ts
  Tasks/HelmDeploy/typings/sinon/sinon.d.ts
  Tasks/HelmDeploy/typings/tsd.d.ts
  make-options.json
Labels: Area: Release

#6603 Using typed-rest-client instead of request in JenkinsRestClient.
  Tasks/JenkinsDownloadArtifacts/ArtifactDetails/JenkinsRestClient.ts
  Tasks/JenkinsDownloadArtifacts/package-lock.json
  Tasks/JenkinsDownloadArtifacts/package.json
  Tasks/JenkinsDownloadArtifacts/task.json
  Tasks/JenkinsDownloadArtifacts/task.loc.json
  package-lock.json
Labels: Area: Release

#6611 Added secrets section in Kubernetes Task
  Tasks/Kubernetes/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Kubernetes/Tests/L0.ts
  Tasks/Kubernetes/Tests/TestSetup.ts
  Tasks/Kubernetes/Tests/TestShared.ts
  Tasks/Kubernetes/src/kubernetes.ts
  Tasks/Kubernetes/src/kubernetessecret.ts
  Tasks/Kubernetes/task.json
  Tasks/Kubernetes/task.loc.json
Labels: Area: Release

#6613 SqlAzureDacpacDeployment: Bug fix for firewall Auto-Detect
  Tasks/SqlAzureDacpacDeployment/DeploySqlAzure.ps1
  Tasks/SqlAzureDacpacDeployment/README.md
  Tasks/SqlAzureDacpacDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/SqlAzureDacpacDeployment/Tests/L0UtilityIPRange.ps1
  Tasks/SqlAzureDacpacDeployment/Utility.ps1
  Tasks/SqlAzureDacpacDeployment/task.json
  Tasks/SqlAzureDacpacDeployment/task.loc.json
Labels: Area: Release

#6517 Updating to lower versions of modules in AzureVMSSDeployment Task
  Tasks/AzureVmssDeployment/ThirdPartyNotices.txt
  Tasks/AzureVmssDeployment/package-lock.json
Labels: Area: Release

#6520 Updating to lower versions of modules in AzureVMSSDeployment Task
  Tasks/AzureVmssDeployment/ThirdPartyNotices.txt
  Tasks/AzureVmssDeployment/package-lock.json
Labels: Area: Release

#6636 Create ThirdPartyNotices.txt
  Tasks/DownloadBuildArtifacts/ThirdPartyNotices.txt
Labels: Area: Release

#6467 Added support for custom certificates
  Tasks/AzureCloudPowerShellDeployment/Publish-AzureCloudDeployment.ps1
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/de-de/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/es-es/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/fr-fr/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/it-IT/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/ja-jp/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/ko-KR/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/ru-RU/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/zh-CN/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/zh-TW/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Utility.ps1
  Tasks/AzureCloudPowerShellDeployment/task.json
  Tasks/AzureCloudPowerShellDeployment/task.loc.json
Labels: Area: Release

#6547 added doc for updateReleaseName in authoring doc file
  docs/authoring/commands.md
Labels: Area: Release

#6685 SqlAzureDacpacDeployment: Bug fix for firewall Auto-Detect (#6613)
  Tasks/SqlAzureDacpacDeployment/DeploySqlAzure.ps1
  Tasks/SqlAzureDacpacDeployment/README.md
  Tasks/SqlAzureDacpacDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/SqlAzureDacpacDeployment/Tests/L0UtilityIPRange.ps1
  Tasks/SqlAzureDacpacDeployment/Utility.ps1
  Tasks/SqlAzureDacpacDeployment/task.json
  Tasks/SqlAzureDacpacDeployment/task.loc.json
Labels: Area: Release

#6268 Support artifacts published from any location
  Tasks/ServiceFabricUpdateManifests/Strings/resources.resjson/en-US/resources.resjson
  Tasks/ServiceFabricUpdateManifests/Tests/L0.ts
  Tasks/ServiceFabricUpdateManifests/Tests/Test-ApplicationVersions.ps1
  Tasks/ServiceFabricUpdateManifests/Tests/Update-ApplicationVersions.NoChanges.SubPath.ps1
  Tasks/ServiceFabricUpdateManifests/Tests/Update-ApplicationVersions.ServiceChanged.SubPath.ps1
  Tasks/ServiceFabricUpdateManifests/Update-ApplicationVersions.psm1
  Tasks/ServiceFabricUpdateManifests/task.json
  Tasks/ServiceFabricUpdateManifests/task.loc.json
Labels: Area: Build, Area: Release, Area: ServiceFabric

#6673 Use agent's temp dir if available
  Tasks/Common/PowershellHelpers/Helpers.ps1
  Tasks/Common/PowershellHelpers/PowershellHelpers.psm1
  Tasks/Common/PowershellHelpers/Tests/Get-TempDirectoryPath.ps1
  Tasks/Common/PowershellHelpers/Tests/Invoke-ActionWithRetries.ShouldHandleMultipleRetryableExceptions.ps1
  Tasks/Common/PowershellHelpers/Tests/L0.ts
  Tasks/ServiceFabricDeploy/Create-DiffPackage.psm1
  Tasks/ServiceFabricDeploy/ServiceFabricSDK/Publish-NewServiceFabricApplication.ps1
  Tasks/ServiceFabricDeploy/ServiceFabricSDK/Publish-UpgradedServiceFabricApplication.ps1
  Tasks/ServiceFabricDeploy/ServiceFabricSDK/Utilities.ps1
  Tasks/ServiceFabricDeploy/Strings/resources.resjson/en-US/resources.resjson
  Tasks/ServiceFabricDeploy/Tests/CreateDiffPkg.ps1
  Tasks/ServiceFabricDeploy/task.json
  Tasks/ServiceFabricDeploy/task.loc.json
  Tasks/ServiceFabricUpdateManifests/Get-VstsBuild.psm1
  Tasks/ServiceFabricUpdateManifests/make.json
  Tasks/ServiceFabricUpdateManifests/task.json
  Tasks/ServiceFabricUpdateManifests/task.loc.json
Labels: Area: Release

#6526 adding task documentation
  Tasks/GoTool/README.md
Labels: Area: Release

#6528 adding task documentation
  Tasks/Go/README.md
Labels: Area: Release

#6690 Force member update
  Tasks/PowerShellOnTargetMachines/PowerShellJob.ps1
  Tasks/PowerShellOnTargetMachines/task.json
  Tasks/PowerShellOnTargetMachines/task.loc.json
Labels: Area: Release

#6704 Virtual Application - Output variable fix
  Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeployment/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: AzureAppService, Area: Release

#6712 Virtual Application Fix M132
  Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeployment/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: AzureAppService, Area: Release

#6713 Virtual Application output variable M131
  Tasks/AzureRmWebAppDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeployment/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: AzureAppService, Area: Release

#6639 Stop special handling of exportPath in VSTS Xcode task
  Tasks/Xcode/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Xcode/Tests/L0.ts
  Tasks/Xcode/Tests/L0CreateIpaWithCodeSigningIdentifiers.ts
  Tasks/Xcode/Tests/L0ExportArchiveAtSpecificPath.ts
  Tasks/Xcode/Tests/L0ExportArchiveSpecify.ts
  Tasks/Xcode/Tests/L0ExportArchiveWithAuto.ts
  Tasks/Xcode/Tests/L0ExportArchiveWithPlist.ts
  Tasks/Xcode/Tests/L0ExportOptionsPlistBadPath.ts
  Tasks/Xcode/Tests/L0FilePathForArchiveAndExportPath.ts
  Tasks/Xcode/Tests/L0TaskDefaults_4.127.0.ts
  Tasks/Xcode/Tests/L0XCode9SigningDefaultsToAutoWithAutoExport.ts
  Tasks/Xcode/Tests/L0XCode9SigningDefaultsToManualWithAutoExport.ts
  Tasks/Xcode/Tests/L0Xcode8AutomaticSignWithDevTeam.ts
  Tasks/Xcode/Tests/L0Xcode8AutomaticSignWithIdentifiers.ts
  Tasks/Xcode/Tests/L0Xcode9AutomaticSignWithAllowProvisioningUpdates.ts
  Tasks/Xcode/Tests/L0Xcode9AutomaticSignWithFiles.ts
  Tasks/Xcode/Tests/L0Xcode9ExportArchiveWithAutoAndCloudEntitlementForDevelopment.ts
  Tasks/Xcode/Tests/L0Xcode9ExportArchiveWithAutoAndCloudEntitlementForProduction.ts
  Tasks/Xcode/Tests/L0XcodeArchiveExportProject.ts
  Tasks/Xcode/Tests/L0macOSAutoExport.ts
  Tasks/Xcode/Tests/L0macOSProvisionlessAutoExport.ts
  Tasks/Xcode/package-lock.json
  Tasks/Xcode/task.json
  Tasks/Xcode/task.loc.json
  Tasks/Xcode/xcode.ts
  Tests-Legacy/L0/Xcode/_suite.ts
  Tests-Legacy/L0/Xcode/responseDefaultInputs.json
  Tests-Legacy/L0/Xcode/responseOptionalArgs.json
  Tests-Legacy/L0/Xcode/responseProject.json
  Tests-Legacy/L0/Xcode/responseSigningFile.json
  Tests-Legacy/L0/Xcode/responseSigningId.json
  Tests-Legacy/L0/Xcode/responseXcpretty.json
Labels: Area: CrossPlatform, Area: Mobile

#6637 Bug fix 1199756 - More Information of agentless task navigates to a wrong page
  Tasks/AzureFunction/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFunction/task.json
  Tasks/AzureFunction/task.loc.json
  Tasks/AzureMonitor/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureMonitor/task.json
  Tasks/AzureMonitor/task.loc.json
  Tasks/Delay/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Delay/task.json
  Tasks/Delay/task.loc.json
  Tasks/InvokeRestApi/Strings/resources.resjson/en-US/resources.resjson
  Tasks/InvokeRestApi/task.json
  Tasks/InvokeRestApi/task.loc.json
  Tasks/ManualIntervention/Strings/resources.resjson/en-US/resources.resjson
  Tasks/ManualIntervention/task.json
  Tasks/ManualIntervention/task.loc.json
  Tasks/PublishToAzureServiceBus/Strings/resources.resjson/en-US/resources.resjson
  Tasks/PublishToAzureServiceBus/task.json
  Tasks/PublishToAzureServiceBus/task.loc.json
  Tasks/QueryWorkItems/Strings/resources.resjson/en-US/resources.resjson
  Tasks/QueryWorkItems/task.json
  Tasks/QueryWorkItems/task.loc.json
Labels: Area: Release

#6730 Users/arjgupta/azureps fix master
  Tasks/AzureCloudPowerShellDeployment/task.json
  Tasks/AzureCloudPowerShellDeployment/task.loc.json
  Tasks/AzureFileCopy/task.json
  Tasks/AzureFileCopy/task.loc.json
  Tasks/AzurePowerShell/task.json
  Tasks/AzurePowerShell/task.loc.json
  Tasks/Common/VstsAzureHelpers_/ImportFunctions.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ValidatesRMProfileFound.ps1
Labels: Area: Release

#6602 updated contact info
  Tasks/SqlDacpacDeploymentOnMachineGroup/README.md
Labels: Area: Release

#6601 updated contact info
  Tasks/SqlAzureDacpacDeployment/README.md
Labels: Area: Release

#6600 updated contact info
  Tasks/IISWebAppManagementOnMachineGroup/README.md
Labels: Area: Release

#6599 Updated contact info
  Tasks/IISWebAppDeploymentOnMachineGroup/README.md
Labels: Area: Release

#6598 updated contact info
  Tasks/DotNetCoreInstaller/README.md
Labels: Area: Release

#6597 updated contact info
  Tasks/DotNetCoreCLI/README.md
Labels: Area: Release

#6596 updated contact info
  Tasks/AzureRmWebAppDeployment/README.md
Labels: Area: Release

#6595 updated contact info
  Tasks/AzureMysqlDeployment/README.md
Labels: Area: Release

#6594 updated contact info
  Tasks/AzureMonitorAlerts/README.md
Labels: Area: Release

#6593 updated contact info
  Tasks/AzureResourceGroupDeployment/README.md
Labels: Area: Release

#6572 Updated contact info
  Tasks/AzureKeyVault/README.md
Labels: Area: Release

#6571 Updated contact info
  Tasks/AzureFileCopy/README.md
Labels: Area: Release

#6570 Updated contact info
  Tasks/AzureCLI/Readme.md
Labels: Area: Release

#6569 Updated contact info
  Tasks/AzureAppServiceManage/README.md
Labels: Area: Release

#6274 Set the console code page to "UTF-8"
  Tasks/DotNetCoreCLI/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DotNetCoreCLI/dotnetcore.ts
  Tasks/DotNetCoreCLI/task.json
  Tasks/DotNetCoreCLI/task.loc.json
Labels: Area: Release

#6758 Fix for taking TestRun title into consideration while publishing results
  Tasks/ANT/anttask.ts
  Tasks/ANT/task.json
  Tasks/ANT/task.loc.json
Labels: Area: CrossPlatform

#6356 DownloadBuildArtifacts - Use latest build filtered by branch
  Tasks/DownloadBuildArtifacts/main.ts
  Tasks/DownloadBuildArtifacts/task.json
Labels: Area: Release

#6591 Add "Use Python Version" task
  Tasks/UsePythonVersion/Strings/resources.resjson/en-US/resources.resjson
  Tasks/UsePythonVersion/Tests/L0.ts
  Tasks/UsePythonVersion/Tests/package-lock.json
  Tasks/UsePythonVersion/Tests/package.json
  Tasks/UsePythonVersion/ThirdPartyNotice.txt
  Tasks/UsePythonVersion/icon.png
  Tasks/UsePythonVersion/main.ts
  Tasks/UsePythonVersion/package-lock.json
  Tasks/UsePythonVersion/package.json
  Tasks/UsePythonVersion/task.json
  Tasks/UsePythonVersion/task.loc.json
  Tasks/UsePythonVersion/tsconfig.json
  Tasks/UsePythonVersion/usepythonversion.ts
  make-options.json
Labels: Area: CrossPlatform

#6767 Using artifact engine 0.1.18 to get latest fix on the resource file s…
  Tasks/DownloadBuildArtifacts/package-lock.json
  Tasks/DownloadBuildArtifacts/package.json
  Tasks/JenkinsDownloadArtifacts/package-lock.json
  Tasks/JenkinsDownloadArtifacts/package.json
  Tasks/JenkinsDownloadArtifacts/task.json
  Tasks/JenkinsDownloadArtifacts/task.loc.json
Labels: Area: Release

#6773 Using artifact engine 0.1.18 to get latest fix on the resource file s…
  Tasks/DownloadBuildArtifacts/package-lock.json
  Tasks/DownloadBuildArtifacts/package.json
  Tasks/DownloadBuildArtifacts/task.json
  Tasks/DownloadBuildArtifacts/task.loc.json
  Tasks/JenkinsDownloadArtifacts/package-lock.json
  Tasks/JenkinsDownloadArtifacts/package.json
  Tasks/JenkinsDownloadArtifacts/task.json
  Tasks/JenkinsDownloadArtifacts/task.loc.json
Labels: Area: Release

#6774 Using artifact engine 0.1.18 to get latest fix on the resource file s…
  Tasks/DownloadBuildArtifacts/package-lock.json
  Tasks/DownloadBuildArtifacts/package.json
  Tasks/DownloadBuildArtifacts/task.json
  Tasks/DownloadBuildArtifacts/task.loc.json
  Tasks/JenkinsDownloadArtifacts/package-lock.json
  Tasks/JenkinsDownloadArtifacts/package.json
  Tasks/JenkinsDownloadArtifacts/task.json
  Tasks/JenkinsDownloadArtifacts/task.loc.json
Labels: Area: Release

#5000 Download Node from fallback location if not in normal location.
  Tasks/NodeTool/nodetool.ts
Labels: Area: Core

#6645 Add support for nuget pack -basepath
  Tasks/NuGetCommand/Strings/resources.resjson/en-US/resources.resjson
  Tasks/NuGetCommand/Tests/L0.ts
  Tasks/NuGetCommand/Tests/PackTests/packBasePath.ts
  Tasks/NuGetCommand/nugetcommandmain.ts
  Tasks/NuGetCommand/nugetpack.ts
  Tasks/NuGetCommand/package-lock.json
  Tasks/NuGetCommand/package.json
  Tasks/NuGetCommand/task.json
  Tasks/NuGetCommand/task.loc.json
Labels: Area: Packaging

#6784 Fixing typo
  Tasks/DownloadBuildArtifacts/main.ts
Labels: Area: Release

#6725 fix azurerm.profile import logic to use get-module instead of looking…
  Tasks/AzureCloudPowerShellDeployment/task.json
  Tasks/AzureCloudPowerShellDeployment/task.loc.json
  Tasks/AzureFileCopy/task.json
  Tasks/AzureFileCopy/task.loc.json
  Tasks/AzurePowerShell/task.json
  Tasks/AzurePowerShell/task.loc.json
  Tasks/Common/VstsAzureHelpers_/ImportFunctions.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ValidatesRMProfileFound.ps1
Labels: Area: Release

#6765 Fix for key vault task failing for multi line secret with regexp
  Tasks/AzureKeyVault/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureKeyVault/operations/KeyVault.ts
  Tasks/AzureKeyVault/task.json
  Tasks/AzureKeyVault/task.loc.json
Labels: Area: Release

#6764 Fix for key vault task failing for multi line secret with regexp
  Tasks/AzureKeyVault/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureKeyVault/operations/KeyVault.ts
  Tasks/AzureKeyVault/task.json
  Tasks/AzureKeyVault/task.loc.json
Labels: Area: Release

#6794 resolve merge conflicts
  Tasks/AzureCloudPowerShellDeployment/task.json
  Tasks/AzureCloudPowerShellDeployment/task.loc.json
  Tasks/AzureFileCopy/task.json
  Tasks/AzureFileCopy/task.loc.json
  Tasks/AzurePowerShell/task.json
  Tasks/AzurePowerShell/task.loc.json
  Tasks/Common/VstsAzureHelpers_/ImportFunctions.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ValidatesRMProfileFound.ps1
Labels: Area: Release

#6779 Users/suaggar/webdeploytlsguidancemsg
  Tasks/AzureRmWebAppDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/webdeployment-common/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/webdeployment-common/module.json
  Tasks/Common/webdeployment-common/msdeployutility.ts
  Tasks/IISWebAppDeploymentOnMachineGroup/Strings/resources.resjson/en-US/resources.resjson
  Tasks/IISWebAppDeploymentOnMachineGroup/task.json
  Tasks/IISWebAppDeploymentOnMachineGroup/task.loc.json
Labels: Area: AzureAppService, Area: Release

#6703 [ServiceFabricComposeDeploy] Sanitize compose application name for SDK version >= 2.8
  Tasks/ServiceFabricComposeDeploy/ServiceFabricComposeDeploy.ps1
  Tasks/ServiceFabricComposeDeploy/Strings/resources.resjson/en-US/resources.resjson
  Tasks/ServiceFabricComposeDeploy/Tests/Deploy.2.8.ps1
  Tasks/ServiceFabricComposeDeploy/Tests/Upgrade.2.8.ps1
  Tasks/ServiceFabricComposeDeploy/task.json
  Tasks/ServiceFabricComposeDeploy/task.loc.json
  Tasks/ServiceFabricComposeDeploy/utilities.ps1
Labels: Area: Release

#6750 Supporting simultaneous update.
  Tasks/AzureCloudPowerShellDeployment/Publish-AzureCloudDeployment.ps1
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/de-de/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/es-es/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/fr-fr/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/it-IT/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/ja-jp/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/ko-KR/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/ru-RU/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/zh-CN/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/Strings/resources.resjson/zh-TW/resources.resjson
  Tasks/AzureCloudPowerShellDeployment/task.json
  Tasks/AzureCloudPowerShellDeployment/task.loc.json
Labels: Area: Release

#6799 Users/suaggar/porttom131
  Tasks/AzureRmWebAppDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/webdeployment-common/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/webdeployment-common/module.json
  Tasks/Common/webdeployment-common/msdeployutility.ts
  Tasks/IISWebAppDeploymentOnMachineGroup/Strings/resources.resjson/en-US/resources.resjson
  Tasks/IISWebAppDeploymentOnMachineGroup/task.json
  Tasks/IISWebAppDeploymentOnMachineGroup/task.loc.json
Labels: Area: Release

#6800 Users/suaggar/porttom132
  Tasks/AzureRmWebAppDeployment/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
  Tasks/Common/webdeployment-common/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/webdeployment-common/module.json
  Tasks/Common/webdeployment-common/msdeployutility.ts
  Tasks/IISWebAppDeploymentOnMachineGroup/Strings/resources.resjson/en-US/resources.resjson
  Tasks/IISWebAppDeploymentOnMachineGroup/task.json
  Tasks/IISWebAppDeploymentOnMachineGroup/task.loc.json
Labels: Area: Release

#6763 Update task.json
  Tasks/DownloadBuildArtifacts/task.json
  Tasks/DownloadBuildArtifacts/task.loc.json
Labels: Area: Release

#6762 Update task.json
  Tasks/DownloadBuildArtifacts/task.json
  Tasks/DownloadBuildArtifacts/task.loc.json
Labels: Area: Release

#6646 Added configMaps section in Kubernetes
  Tasks/Kubernetes/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Kubernetes/Tests/L0.ts
  Tasks/Kubernetes/Tests/TestSetup.ts
  Tasks/Kubernetes/Tests/TestShared.ts
  Tasks/Kubernetes/src/clusterconnection.ts
  Tasks/Kubernetes/src/kubernetes.ts
  Tasks/Kubernetes/src/kubernetescommand.ts
  Tasks/Kubernetes/src/kubernetesconfigmap.ts
  Tasks/Kubernetes/src/kubernetessecret.ts
  Tasks/Kubernetes/src/utilities.ts
  Tasks/Kubernetes/task.json
  Tasks/Kubernetes/task.loc.json
Labels: Area: Release

#6747 Number of slashes between url and remote path should now be exactly one
  Tasks/cURLUploader/curluploader.ts
  Tasks/cURLUploader/task.json
Labels: Area: CrossPlatform

#6822 added Q-param for siteextensions api - Kudu Service
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
  Tasks/Common/azure-arm-rest/Tests/mock_utils.ts
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#6809 Supporting AppService task on Deployment Group
  Tasks/AzureAppServiceManage/task.json
  Tasks/AzureAppServiceManage/task.loc.json
  Tasks/AzureRmWebAppDeployment/task.json
  Tasks/AzureRmWebAppDeployment/task.loc.json
Labels: Area: AzureAppService, Area: Release

#6812 Microsoft/users/raagra/tls12 support for powershell tasks
  Tasks/AzureCloudPowerShellDeployment/make.json
  Tasks/AzureCloudPowerShellDeployment/task.json
  Tasks/AzureCloudPowerShellDeployment/task.loc.json
  Tasks/AzureFileCopy/make.json
  Tasks/AzureFileCopy/task.json
  Tasks/AzureFileCopy/task.loc.json
  Tasks/AzurePowerShell/make.json
  Tasks/AzurePowerShell/task.json
  Tasks/AzurePowerShell/task.loc.json
  Tasks/Common/TlsHelper_/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/TlsHelper_/TlsHelper_.psm1
  Tasks/Common/TlsHelper_/module.json
  Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.AzurePreferredFallsBack.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.AzureRMPreferredFallsBack.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.BothPreferredFallsBack.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.ThrowsWhenNotFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.ValidatesClassicVersion.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ImportsModules.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ReturnsFalseWhenNotFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ValidatesRMProfileFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromSdkPath.ImportsModule.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromSdkPath.ReturnsFalseWhenNotFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-Azure.PassesInputs.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-Azure.ThrowsWhenServiceNameIsNull.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenAzureStackSPAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenCertAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenCertAuthAndEnvironment.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenSPAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenUPAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsUsefulErrorWhenSPAuthAndAddAccountFails.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsUsefulErrorWhenUPAuthAndAddAccountFails.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsWhenRMAndCertAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsWhenSPAuthAndClassic099.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsWhenUnsupportedAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/OverriddesGlobalDebugPreference.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Set-CurrentAzureRMSubscription.PassesValues.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Set-CurrentAzureSubscription.PassesValues.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Set-UserAgent.PassesValues.ps1
  Tasks/Common/VstsAzureHelpers_/VstsAzureHelpers_.psm1
  Tasks/Common/VstsAzureRestHelpers_/Tests/Get-AzureActiveDirectoryResourceId.ps1
  Tasks/Common/VstsAzureRestHelpers_/Tests/Populate-AzureStackDependencyData.ps1
  Tasks/Common/VstsAzureRestHelpers_/VstsAzureRestHelpers_.psm1
  Tasks/SqlAzureDacpacDeployment/make.json
  Tasks/SqlAzureDacpacDeployment/task.json
  Tasks/SqlAzureDacpacDeployment/task.loc.json
Labels: Area: Release
