Repository microsoft/azure-pipelines-tasks, pull requests merged in 2018-09, with the labels that each got.

#8154 Fixing the download build artifact issue where if forward slash is me…
  Tasks/DownloadBuildArtifactsV0/main.ts
  Tasks/DownloadBuildArtifactsV0/task.json
  Tasks/DownloadBuildArtifactsV0/task.loc.json
Labels: Area: Release

#8027 L0 for app service Deploy task
  Tasks/AzureRmWebAppDeploymentV4/Tests/AzureRmWebAppDeploymentProviderL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/AzureRmWebAppDeploymentProviderTests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/BuiltInLinuxWebAppDeploymentProviderL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/BuiltInLinuxWebAppDeploymentProviderTests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/ContainerWebAppDeploymentProviderL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/ContainerWebAppDeploymentProviderTests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/DeploymentFactoryL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/DeploymentFactoryTests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/L0.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/PublishProfileWebAppDeploymentProviderL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/PublishProfileWebAppDeploymentProviderTests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/WindowsWebAppRunFromZipProviderL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/WindowsWebAppRunFromZipProviderTests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/WindowsWebAppWarDeployProviderL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/WindowsWebAppWarDeployProviderTests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/WindowsWebAppWebDeployProviderL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/WindowsWebAppWebDeployProviderTests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/WindowsWebAppZipDeployProviderL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/WindowsWebAppZipDeployProviderTests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/mock_utils.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/utils.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/AzureRmWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/KuduServiceUtility.ts
Labels: Area: Release

#8231 Updated the task documentation for 4.* version @vincentdass @kmkumaran
  Tasks/AzureRmWebAppDeploymentV4/README.md
Labels: Area: AzureAppService, Area: Release

#8228 Reducing the query size of definitions API to prevent 2 MB limit error
  Tasks/DownloadBuildArtifactsV0/task.json
  Tasks/DownloadBuildArtifactsV0/task.loc.json
Labels: Area: Release

#8260 Add xcWorkspacePath to Xcode template
  templates/ci/xcode.yml
Labels: Area: CrossPlatform

#8269 Dynamic Runtime stack operation - Azure App Service Deploy
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
Labels: Area: AzureAppService, Area: Release

#8279 Fix minor issue of AzureCLI Task
  Tasks/AzureCLIV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureCLIV1/azureclitask.ts
  Tasks/AzureCLIV1/task.json
  Tasks/AzureCLIV1/task.loc.json
Labels: Area: Release

#8268 Azure App Service Deploy - Fix post deployment script
  Tasks/AzureRmWebAppDeploymentV3/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV3/operations/KuduServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV3/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/Tests/L0.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/TaskParametersLinuxAppL0Tests.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/TaskParametersTests.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/KuduServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#8281 Add BuildSourcesDirectory in InputDataContract.
  Tasks/VsTestV2/inputdatacontract.ts
  Tasks/VsTestV2/inputparser.ts
  Tasks/VsTestV2/make.json
  Tasks/VsTestV2/task.json
  Tasks/VsTestV2/task.loc.json
Labels: Area: Test, Area: TestManagement

#8296 Post Deployment script - addressed review comments
  Tasks/AzureRmWebAppDeploymentV3/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/TaskParameters.ts
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/azure-arm-rest/webClient.ts
Labels: Area: AzureAppService, Area: Release

#8287 Users/vinca/pdfix m140
  Tasks/AzureRmWebAppDeploymentV4/operations/KuduServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/azure-arm-rest/webClient.ts
Labels: Area: AzureAppService, Area: Release

#8275 Port dynamic runtime stack changes to M140
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
Labels: Area: AzureAppService, Area: Release

#8349 Fix RetryTimedout
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#8357 Bump up artifact engine version
  Tasks/DownloadBuildArtifactsV0/package.json
  Tasks/DownloadFileshareArtifactsV0/package.json
  Tasks/DownloadFileshareArtifactsV0/task.json
  Tasks/DownloadFileshareArtifactsV0/task.loc.json
  Tasks/JenkinsDownloadArtifactsV1/package.json
  Tasks/JenkinsDownloadArtifactsV1/task.json
  Tasks/JenkinsDownloadArtifactsV1/task.loc.json
Labels: Area: Release

#8183 Added output variable support for DockerV0 and DockerV1 tasks
  Tasks/DockerV0/container.ts
  Tasks/DockerV0/containercommand.ts
  Tasks/DockerV0/task.json
  Tasks/DockerV0/task.loc.json
  Tasks/DockerV1/container.ts
  Tasks/DockerV1/containercommand.ts
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
Labels: Area: Release

#8399 Add azure policy assessment gate preview
  Tasks/AzurePolicyV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzurePolicyV0/icon.png
  Tasks/AzurePolicyV0/task.json
  Tasks/AzurePolicyV0/task.loc.json
  Tests/L0.ts
Labels: Area: Release

#8215 Added azure stack support to key vault task
  Tasks/AzureKeyVaultV1/main.ts
  Tasks/AzureKeyVaultV1/models/KeyVaultTaskParameters.ts
  Tasks/AzureKeyVaultV1/operations/azure-arm-keyvault.ts
  Tasks/AzureKeyVaultV1/task.json
  Tasks/AzureKeyVaultV1/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-endpoint.ts
  Tasks/Common/azure-arm-rest/azureModels.ts
  Tasks/Common/azurestack-common/azurestackrestutility.ts
Labels: Area: Release

#8381 Convert docker/helm/docker-compose command input to lowercase
  Tasks/DockerComposeV0/dockercompose.ts
  Tasks/DockerComposeV0/task.json
  Tasks/DockerComposeV0/task.loc.json
  Tasks/DockerV0/container.ts
  Tasks/DockerV0/task.json
  Tasks/DockerV0/task.loc.json
  Tasks/DockerV1/container.ts
  Tasks/HelmDeployV0/src/helm.ts
  Tasks/HelmDeployV0/task.json
  Tasks/HelmDeployV0/task.loc.json
Labels: Area: Release

#8405 Removing preview from mysql task
  Tasks/AzureMysqlDeploymentV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureMysqlDeploymentV1/task.json
  Tasks/AzureMysqlDeploymentV1/task.loc.json
Labels: Area: Release

#8384 Adding the search use case to the build definition data source
  Tasks/DownloadBuildArtifactsV0/task.json
  Tasks/DownloadBuildArtifactsV0/task.loc.json
Labels: Area: Release
