Repository microsoft/azure-pipelines-tasks, pull requests merged in 2018-08, with the labels that each got.

#7678 Certificate support in Azure RM endpoint
  Tasks/AzureAppServiceManageV0/azureappservicemanage.ts
  Tasks/AzureAppServiceManageV0/package-lock.json
  Tasks/AzureAppServiceManageV0/task.json
  Tasks/AzureAppServiceManageV0/task.loc.json
  Tasks/AzureFileCopyV2/package-lock.json
  Tasks/AzureFileCopyV2/package.json
  Tasks/AzureKeyVaultV1/npm-shrinkwrap.json
  Tasks/AzureKeyVaultV1/package.json
  Tasks/AzureMonitorAlertsV0/npm-shrinkwrap.json
  Tasks/AzureMonitorAlertsV0/package.json
  Tasks/AzureMysqlDeploymentV1/package-lock.json
  Tasks/AzureMysqlDeploymentV1/package.json
  Tasks/AzureResourceGroupDeploymentV2/package-lock.json
  Tasks/AzureResourceGroupDeploymentV2/package.json
  Tasks/AzureRmWebAppDeploymentV3/package-lock.json
  Tasks/AzureRmWebAppDeploymentV3/package.json
  Tasks/AzureRmWebAppDeploymentV4/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeploymentV4/package-lock.json
  Tasks/AzureRmWebAppDeploymentV4/package.json
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/AzureVmssDeploymentV0/package-lock.json
  Tasks/AzureVmssDeploymentV0/package.json
  Tasks/Common/azure-arm-rest/azure-arm-common.ts
  Tasks/Common/azure-arm-rest/azure-arm-endpoint.ts
  Tasks/Common/azure-arm-rest/azureModels.ts
  Tasks/Common/azure-arm-rest/constants.ts
  Tasks/Common/azure-arm-rest/make.json
  Tasks/Common/azure-arm-rest/package-lock.json
  Tasks/Common/azure-arm-rest/package.json
  Tasks/HelmDeployV0/package-lock.json
  Tasks/HelmDeployV0/package.json
  Tasks/JavaToolInstallerV0/package-lock.json
  Tasks/JavaToolInstallerV0/package.json
  Tasks/JenkinsDownloadArtifactsV1/package-lock.json
  Tasks/JenkinsDownloadArtifactsV1/package.json
  Tasks/KubernetesV1/npm-shrinkwrap.json
  Tasks/KubernetesV1/package.json
  Tasks/PackerBuildV0/package-lock.json
  Tasks/PackerBuildV0/package.json
Labels: Area: AzureAppService, Area: Release

#7904 [SqlAzureDacpacDeployment] Bug fix for missing cmdlet
  Tasks/SqlAzureDacpacDeploymentV1/DeploySqlAzure.ps1
  Tasks/SqlAzureDacpacDeploymentV1/make.json
  Tasks/SqlAzureDacpacDeploymentV1/task.json
  Tasks/SqlAzureDacpacDeploymentV1/task.loc.json
Labels: Area: Release

#7894 patch version
  Tasks/DownloadFileshareArtifactsV0/task.json
  Tasks/DownloadFileshareArtifactsV0/task.loc.json
Labels: Area: Release

#7905 [AzureRGDeploy] Fixing unhandled reject
  Tasks/AzureResourceGroupDeploymentV2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureResourceGroupDeploymentV2/task.json
  Tasks/AzureResourceGroupDeploymentV2/task.loc.json
  Tasks/Common/azure-arm-rest/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/azure-arm-rest/azure-arm-resource.ts
  Tasks/Common/azure-arm-rest/module.json
  Tasks/Common/azure-arm-rest/webClient.ts
Labels: Area: Release

#7889 Fixed typo in the help text for the Azure App Service Deploy task
  Tasks/AzureRmWebAppDeploymentV3/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/task.json
Labels: Area: AzureAppService, Area: Release

#7919 upgraded patch version for customer contribution
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
Labels: Area: AzureAppService, Area: Release

#7925 Removed comment azure cli is not installed on hosted
  Tasks/AzureCLIV1/Readme.md
Labels: Area: Release

#7931 Run App Service Task on Deployment Group
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
Labels: Area: AzureAppService, Area: Release

#7962 Enable ADFS check - Azure Stack
  Tasks/Common/azure-arm-rest/azure-arm-endpoint.ts
Labels: Area: AzureAppService, Area: Release

#7961 Added support to utilize refreshToken to refresh the access token
  Tasks/ServiceFabricDeployV1/ServiceFabricSDK/Utilities.ps1
  Tasks/ServiceFabricDeployV1/task.json
  Tasks/ServiceFabricDeployV1/task.loc.json
Labels: Area: Release

#7854 Azure App Service Deploy - Fix Parameter parser utility
  Tasks/AzureRmWebAppDeploymentV4/Tests/L0.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/L0GenerateWebConfigForNode.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/L0ParameterParserUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/AzureRmWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppRunFromZipProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/ParameterParserUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/parameterparser.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
Labels: Area: AzureAppService, Area: Release

#7965 Surfacing App & cluster health in case of SF application upgrade failure
  Tasks/ServiceFabricDeployV1/ServiceFabricSDK/Publish-UpgradedServiceFabricApplication.ps1
  Tasks/ServiceFabricDeployV1/ServiceFabricSDK/Utilities.ps1
Labels: Area: Release

#7723 spring boot deployment (WAR & JAR Deployment support) - App Service Deploy task
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/azurermwebappdeployment.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/DeploymentFactory.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppRunFromZipProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppWarDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppWebDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/FileTransformsUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/KuduServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/TaskParameters.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/webdeployment-common/Strings/resources.resjson/en-US/resources.resjson
  Tasks/Common/webdeployment-common/WebConfigTemplates/java_springboot
  Tasks/Common/webdeployment-common/module.json
  Tasks/Common/webdeployment-common/msdeployutility.ts
  Tasks/Common/webdeployment-common/packageUtility.ts
  Tasks/Common/webdeployment-common/utility.ts
  Tasks/Common/webdeployment-common/webconfigutil.ts
Labels: Area: AzureAppService, Area: Release

#7917 Added login logout commands in Docker, Kubernetes and helm tasks.
  Tasks/Common/docker-common/containerconnection.ts
  Tasks/DockerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerV1/container.ts
  Tasks/DockerV1/dockerlogin.ts
  Tasks/DockerV1/dockerlogout.ts
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
  Tasks/HelmDeployV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/HelmDeployV0/src/helm.ts
  Tasks/HelmDeployV0/src/kubernetescli.ts
  Tasks/HelmDeployV0/task.json
  Tasks/HelmDeployV0/task.loc.json
  Tasks/KubernetesV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/KubernetesV1/Tests/L0.ts
  Tasks/KubernetesV1/Tests/TestSetup.ts
  Tasks/KubernetesV1/src/clusterconnection.ts
  Tasks/KubernetesV1/src/kubernetes.ts
  Tasks/KubernetesV1/src/kuberneteslogin.ts
  Tasks/KubernetesV1/src/kuberneteslogout.ts
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
Labels: Area: Release

#7883 Bug fix 1311467- Don't setup kubernets config for helm package command
  Tasks/HelmDeployV0/src/helm.ts
  Tasks/HelmDeployV0/task.json
  Tasks/HelmDeployV0/task.loc.json
Labels: Area: Release

#7949 Support for build, tag, run, push docker commands same as 'build an image'
  Tasks/DockerV1/container.ts
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
Labels: Area: Release

#7763 Fixed Kubernetes task does not use specified version issue
  Tasks/KubernetesV0/Tests/L0.ts
  Tasks/KubernetesV0/src/clusterconnection.ts
  Tasks/KubernetesV0/task.json
  Tasks/KubernetesV0/task.loc.json
  Tasks/KubernetesV1/Tests/L0.ts
  Tasks/KubernetesV1/src/clusterconnection.ts
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
Labels: Area: Release

#7895 fix issue 6991
  Tasks/DownloadBuildArtifactsV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DownloadBuildArtifactsV0/task.json
Labels: Area: Release

#7859 [Helm] Update Helm repo url + default version to 2.9.1
  Tasks/HelmInstallerV0/src/helminstaller.ts
  Tasks/HelmInstallerV0/task.json
  Tasks/HelmInstallerV0/task.loc.json
Labels: Area: Release

#7916 Add Xcode task telemetry.
  Tasks/XcodeV5/task.json
  Tasks/XcodeV5/task.loc.json
  Tasks/XcodeV5/xcode.ts
  Tasks/XcodeV5/xcodeutils.ts
Labels: Area: CrossPlatform

#8048 [AzureRmWebAppDeployment]Release annotations bug fix
  Tasks/AzureRmWebAppDeploymentV3/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-appinsights.ts
  package-lock.json
Labels: Area: Release

#8031 Removed includeLatestTag from docker push command https://github.com/Microsoft/vsts-tasks/issues/7791
  Tasks/DockerV1/Tests/L0.ts
  Tasks/DockerV1/Tests/TestSetup.ts
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
  Tasks/DockerV1/utils.ts
Labels: Area: Release

#8023 Record Java telemetry with feature `TaskHub`.
  Tasks/ANTV1/task.json
  Tasks/ANTV1/task.loc.json
  Tasks/Common/java-common/java-common.ts
  Tasks/Common/utility-common/package-lock.json
  Tasks/GradleV2/package-lock.json
  Tasks/GradleV2/task.json
  Tasks/GradleV2/task.loc.json
  Tasks/MavenV3/task.json
  Tasks/XamarinAndroidV1/task.json
Labels: Area: CrossPlatform

#8049 Users/suaggar/new azure ps
  Tasks/AzurePowerShellV3/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzurePowerShellV3/task.json
  Tasks/AzurePowerShellV3/task.loc.json
Labels: Area: Release

#8075 [AzureRmWebAppDeployment]Release annotations bug fix (#8048)
  Tasks/AzureRmWebAppDeploymentV3/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-appinsights.ts
  package-lock.json
Labels: Area: AzureAppService, Area: Release

#8071 Added check to remove json and yaml output format for kubectl commands that don't support it
  Tasks/KubernetesV0/Tests/L0.ts
  Tasks/KubernetesV0/Tests/TestSetup.ts
  Tasks/KubernetesV0/src/kubernetescommand.ts
  Tasks/KubernetesV0/task.json
  Tasks/KubernetesV0/task.loc.json
  Tasks/KubernetesV1/Tests/L0.ts
  Tasks/KubernetesV1/Tests/TestSetup.ts
  Tasks/KubernetesV1/src/kubernetescommand.ts
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
Labels: Area: Release

#7781 Added proper check for authorizationType in Helm and Kubernetes Tasks
  Tasks/HelmDeployV0/src/clusters/generickubernetescluster.ts
  Tasks/HelmDeployV0/task.json
  Tasks/HelmDeployV0/task.loc.json
  Tasks/KubernetesV0/src/clusterconnection.ts
  Tasks/KubernetesV0/task.json
  Tasks/KubernetesV0/task.loc.json
  Tasks/KubernetesV1/src/clusters/generickubernetescluster.ts
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
Labels: Area: Release

#8086 converting container repository name to lowercase following docker im…
  Tasks/AzureRmWebAppDeploymentV4/operations/ContainerBasedDeploymentUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
Labels: Area: AzureAppService, Area: Release

#8096 Removed retry from Update Deployment & Ping Application
  Tasks/AzureRmWebAppDeploymentV3/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#8099 Removed retry from Update Deployment & Ping Application M138
  Tasks/AzureRmWebAppDeploymentV3/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#8098 Removed retry from Update Deployment & Ping Application M139
  Tasks/AzureRmWebAppDeploymentV3/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#8101 Users/suaggar/azure stack fix
  Tasks/AzureFileCopyV1/task.json
  Tasks/AzureFileCopyV1/task.loc.json
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
  Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1
Labels: Area: Release

#8102 Clear context before azure stack
  Tasks/AzureFileCopyV1/task.json
  Tasks/AzureFileCopyV1/task.loc.json
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
  Tasks/AzurePowerShellV3/task.json
  Tasks/AzurePowerShellV3/task.loc.json
  Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1
Labels: Area: Release

#8120 Zip Deploy - Archive Folder
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppRunFromZipProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
Labels: Area: AzureAppService, Area: Release

#8121 Zip Deploy - Archive Folder package
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppRunFromZipProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/WindowsWebAppZipDeployProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
Labels: Area: AzureAppService, Area: Release

#8109 Use location APIs to fetch service urls.
  Tasks/DownloadPackageV0/download.ts
  Tasks/DownloadPackageV0/make.json
  Tasks/DownloadPackageV0/npm-shrinkwrap.json
  Tasks/DownloadPackageV0/package.json
Labels: Area: Release

#8148 Users/suaggar/function on containers
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/ContainerWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
Labels: Area: AzureAppService, Area: Release

#8170 Fix MSI authentication for node based tasks (#8157)
  Tasks/AzureAppServiceManageV0/task.json
  Tasks/AzureAppServiceManageV0/task.loc.json
  Tasks/AzureKeyVaultV1/task.json
  Tasks/AzureKeyVaultV1/task.loc.json
  Tasks/AzureMonitorAlertsV0/Tests/L0Mocks.ts
  Tasks/AzureMonitorAlertsV0/task.json
  Tasks/AzureMonitorAlertsV0/task.loc.json
  Tasks/AzureMysqlDeploymentV1/task.json
  Tasks/AzureMysqlDeploymentV1/task.loc.json
  Tasks/AzureResourceGroupDeploymentV2/task.json
  Tasks/AzureResourceGroupDeploymentV2/task.loc.json
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureVmssDeploymentV0/task.json
  Tasks/AzureVmssDeploymentV0/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-endpoint.ts
  Tasks/Common/azure-arm-rest/constants.ts
Labels: Area: Release

#8158 Add an additional troubleshooting tip
  Tasks/SqlAzureDacpacDeploymentV1/README.md
Labels: Area: Release

#8189 App Service status code change
  Tasks/AzureAppServiceManageV0/task.json
  Tasks/AzureAppServiceManageV0/task.loc.json
  Tasks/Common/azure-arm-rest/azure-arm-appinsights-webtests.ts
  Tasks/Common/azure-arm-rest/azure-arm-appinsights.ts
Labels: Area: AzureAppService, Area: Release

#8150 remove dependency from DG endptname invisibleinput
  Tasks/AzureResourceGroupDeploymentV2/models/DeployAzureRG.ts
  Tasks/AzureResourceGroupDeploymentV2/task.json
  Tasks/AzureResourceGroupDeploymentV2/task.loc.json
Labels: Area: Release

#8198 Remove retry for ping application (App Service Manage task)
  Tasks/AzureAppServiceManageV0/operations/AzureAppServiceUtils.ts
  Tasks/AzureAppServiceManageV0/task.json
  Tasks/AzureAppServiceManageV0/task.loc.json
Labels: Area: AzureAppService, Area: Release

#8210 Update Help text in container tasks
  Tasks/DockerV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerV0/task.json
  Tasks/DockerV0/task.loc.json
  Tasks/DockerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
  Tasks/HelmDeployV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/HelmDeployV0/task.json
  Tasks/HelmDeployV0/task.loc.json
  Tasks/KubernetesV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/KubernetesV0/task.json
  Tasks/KubernetesV0/task.loc.json
  Tasks/KubernetesV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
Labels: Area: Release
