Repository microsoft/azure-pipelines-tasks, pull requests merged in 2019-05, with the labels that each got.

#10291 Rolling back change of task lib in AzurePowerShellV4
  Tasks/AzurePowerShellV4/azurepowershell.ts
  Tasks/AzurePowerShellV4/package-lock.json
  Tasks/AzurePowerShellV4/package.json
  Tasks/AzurePowerShellV4/task.json
  Tasks/AzurePowerShellV4/task.loc.json
Labels: Area: Release

#10185 [KubManifestV0] Ignore SSL errors conditonally (#10183)
  Tasks/Common/kubernetes-common/kubectl-object-model.ts
  Tasks/KubernetesManifestV0/src/actions/bake.ts
  Tasks/KubernetesManifestV0/src/actions/createSecret.ts
  Tasks/KubernetesManifestV0/src/actions/delete.ts
  Tasks/KubernetesManifestV0/src/actions/deploy.ts
  Tasks/KubernetesManifestV0/src/actions/patch.ts
  Tasks/KubernetesManifestV0/src/actions/promote.ts
  Tasks/KubernetesManifestV0/src/actions/reject.ts
  Tasks/KubernetesManifestV0/src/actions/scale.ts
  Tasks/KubernetesManifestV0/src/connection.ts
  Tasks/KubernetesManifestV0/src/run.ts
  Tasks/KubernetesManifestV0/task.json
  Tasks/KubernetesManifestV0/task.loc.json
Labels: Area: Release

#10349 Java deploy fix
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureWebAppV1/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/AzureRmDeploy-common/operations/AzureAppServiceUtility.ts
  Tasks/Common/AzureRmDeploy-common/webdeployment-common/utility.ts
Labels: Area: AzureAppService, Area: Release

#10304 Azure function app - add python runtime stack
  Tasks/AzureFunctionAppV1/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
Labels: Area: AzureAppService, Area: Release

#10372 Azure Web App Linux - include image name in runtime stack
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
Labels: Area: AzureAppService, Area: Release

#10382 Azure App Service - hotfix JAVA issues (152)
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureWebAppV1/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/AzureRmDeploy-common/operations/AzureAppServiceUtility.ts
  Tasks/Common/AzureRmDeploy-common/webdeployment-common/utility.ts
Labels: Area: AzureAppService, Area: Release

#10383 Azure App Service - hotfix JAVA issues (151)
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureWebAppV1/deploymentProvider/BuiltInLinuxWebAppDeploymentProvider.ts
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/AzureRmDeploy-common/operations/AzureAppServiceUtility.ts
  Tasks/Common/AzureRmDeploy-common/webdeployment-common/utility.ts
Labels: Area: AzureAppService, Area: Release

#10371 Handling multiple subscriptions
  Tasks/AzurePowerShellV4/InitializeAz.ps1
  Tasks/AzurePowerShellV4/task.json
  Tasks/AzurePowerShellV4/task.loc.json
Labels: Area: Release

#10307 Fix markdown link syntax
  Tasks/SqlAzureDacpacDeploymentV1/README.md
Labels: Area: Release

#10522 Add more retries to secure file tasks
  Tasks/AndroidSigningV2/package-lock.json
  Tasks/AndroidSigningV2/task.json
  Tasks/AndroidSigningV2/task.loc.json
  Tasks/AndroidSigningV3/package-lock.json
  Tasks/AndroidSigningV3/task.json
  Tasks/AndroidSigningV3/task.loc.json
  Tasks/Common/securefiles-common/package-lock.json
  Tasks/Common/securefiles-common/securefiles-common.ts
  Tasks/DownloadSecureFileV1/package-lock.json
  Tasks/DownloadSecureFileV1/task.json
  Tasks/DownloadSecureFileV1/task.loc.json
  Tasks/HelmDeployV0/package-lock.json
  Tasks/HelmDeployV0/task.json
  Tasks/HelmDeployV0/task.loc.json
  Tasks/InstallAppleCertificateV2/package-lock.json
  Tasks/InstallAppleCertificateV2/task.json
  Tasks/InstallAppleCertificateV2/task.loc.json
  Tasks/InstallAppleProvisioningProfileV1/package-lock.json
  Tasks/InstallAppleProvisioningProfileV1/task.json
  Tasks/InstallAppleProvisioningProfileV1/task.loc.json
  Tasks/InstallSSHKeyV0/package-lock.json
  Tasks/InstallSSHKeyV0/task.json
  Tasks/InstallSSHKeyV0/task.loc.json
Labels: Area: CrossPlatform

#10424 Azure PS Tasks - update openssl package with config file
  Tasks/AzureCloudPowerShellDeploymentV1/task.json
  Tasks/AzureCloudPowerShellDeploymentV1/task.loc.json
  Tasks/AzureFileCopyV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFileCopyV1/task.json
  Tasks/AzureFileCopyV1/task.loc.json
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
  Tasks/AzureFileCopyV3/task.json
  Tasks/AzureFileCopyV3/task.loc.json
  Tasks/AzurePowerShellV2/task.json
  Tasks/AzurePowerShellV2/task.loc.json
  Tasks/AzurePowerShellV3/task.json
  Tasks/AzurePowerShellV3/task.loc.json
  Tasks/AzurePowerShellV4/task.json
  Tasks/AzurePowerShellV4/task.loc.json
  Tasks/Common/VstsAzureHelpers_/Utility.ps1
  Tasks/Common/VstsAzureHelpers_/make.json
  Tasks/SqlAzureDacpacDeploymentV1/task.json
  Tasks/SqlAzureDacpacDeploymentV1/task.loc.json
Labels: Area: Release

#10518 Azure powershell, file copy, nlb management and azure monitor alerts task
  Tasks/AzureFileCopyV2/PreJobExecutionAzureFileCopy.ts
  Tasks/AzureFileCopyV2/make.json
  Tasks/AzureFileCopyV2/package-lock.json
  Tasks/AzureFileCopyV2/package.json
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
  Tasks/AzureFileCopyV2/tsconfig.json
  Tasks/AzureFileCopyV3/PreJobExecutionAzureFileCopy.ts
  Tasks/AzureFileCopyV3/make.json
  Tasks/AzureFileCopyV3/package-lock.json
  Tasks/AzureFileCopyV3/package.json
  Tasks/AzureFileCopyV3/task.json
  Tasks/AzureFileCopyV3/task.loc.json
  Tasks/AzureFileCopyV3/tsconfig.json
  Tasks/AzureMonitorAlertsV0/Tests/L0.ts
  Tasks/AzureMonitorAlertsV0/Tests/L0AddAlertRuleFails.ts
  Tasks/AzureMonitorAlertsV0/Tests/L0AddAlertsSuccess.ts
  Tasks/AzureMonitorAlertsV0/Tests/L0AlertRuleGetResourceFail.ts
  Tasks/AzureMonitorAlertsV0/Tests/L0AlertRuleNameConflictFail.ts
  Tasks/AzureMonitorAlertsV0/Tests/L0Mocks.ts
  Tasks/AzureMonitorAlertsV0/Tests/L0UpdateAlertsSuccess.ts
  Tasks/AzureMonitorAlertsV0/Tests/package-lock.json
  Tasks/AzureMonitorAlertsV0/Tests/package.json
  Tasks/AzureMonitorAlertsV0/authorizationclient.ts
  Tasks/AzureMonitorAlertsV0/azuremonitoralerts.ts
  Tasks/AzureMonitorAlertsV0/make.json
  Tasks/AzureMonitorAlertsV0/npm-shrinkwrap.json
  Tasks/AzureMonitorAlertsV0/operations/AzureMonitorAlertsUtility.ts
  Tasks/AzureMonitorAlertsV0/package.json
  Tasks/AzureMonitorAlertsV0/task.json
  Tasks/AzureMonitorAlertsV0/task.loc.json
  Tasks/AzureMonitorAlertsV0/tsconfig.json
  Tasks/AzureNLBManagementV1/Tests/L0.ts
  Tasks/AzureNLBManagementV1/Tests/L0ConnectFailNoLB.ts
  Tasks/AzureNLBManagementV1/Tests/L0ConnectSuccess.ts
  Tasks/AzureNLBManagementV1/Tests/L0DisconnectSuccess.ts
  Tasks/AzureNLBManagementV1/Tests/L0TaskFail.ts
  Tasks/AzureNLBManagementV1/Tests/L0TaskFailNetworkInterfaceRG.ts
  Tasks/AzureNLBManagementV1/Tests/L0TaskFailSetNetworkInterface.ts
  Tasks/AzureNLBManagementV1/nlbazureutility.ts
  Tasks/AzureNLBManagementV1/nlbtask.ts
  Tasks/AzureNLBManagementV1/npm-shrinkwrap.json
  Tasks/AzureNLBManagementV1/package.json
  Tasks/AzureNLBManagementV1/task.json
  Tasks/AzureNLBManagementV1/task.loc.json
  Tasks/AzureNLBManagementV1/tsconfig.json
  Tasks/AzurePowerShellV4/azurepowershell.ts
  Tasks/AzurePowerShellV4/make.json
  Tasks/AzurePowerShellV4/package-lock.json
  Tasks/AzurePowerShellV4/package.json
  Tasks/AzurePowerShellV4/task.json
  Tasks/AzurePowerShellV4/task.loc.json
  Tasks/AzurePowerShellV4/tsconfig.json
Labels: Area: Release
