Repository microsoft/azure-pipelines-tasks, pull requests merged in 2019-01, with the labels that each got.

#9184 Fixing test failure in linux and mac agents and addressing previous c…
  Tasks/GitHubReleaseV0/Tests/ChangeLogL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/ChangeLogTests.ts
  Tasks/GitHubReleaseV0/Tests/TestStrings.ts
  Tasks/GitHubReleaseV0/Tests/UtilityL0Tests.ts
Labels: Area: Release

#9143 Making repository name input as editable.
  Tasks/GitHubReleaseV0/task.json
Labels: Area: Release

#9189 Users/shmittal/utility change
  Tasks/AzurePowerShellV4/AzurePowerShell.ps1
  Tasks/AzurePowerShellV4/Utility.ps1
  Tasks/Common/VstsAzureHelpers_/InitializeAzModuleFunctions.ps1
Labels: Area: Release

#9029 Add rollout status to commands in KubernetesV1 task
  Tasks/KubernetesV1/Tests/L0.ts
  Tasks/KubernetesV1/Tests/TestSetup.ts
  Tasks/KubernetesV1/Tests/TestShared.ts
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
Labels: Area: Release

#9216 Getting the VSTS_HTTP_RETRY option correctly. Setting to zero will di…
  Tasks/JenkinsDownloadArtifactsV1/ArtifactDetails/JenkinsRestClient.ts
  Tasks/JenkinsDownloadArtifactsV1/Tests/JenkinsTestHelper.ts
  Tasks/JenkinsDownloadArtifactsV1/Tests/L0.ts
  Tasks/JenkinsDownloadArtifactsV1/Tests/L0ShouldRetryCorrectlyWhenErrorHappens.ts
Labels: Area: Release

#9225 Users/suaggar/newtask text change
  .github/CODEOWNERS
  Tasks/AzureFunctionAppContainerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppContainerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/FileTransformV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/FileTransformV1/task.json
Labels: Area: AzureAppService, Area: Release

#9208 Added AzureMonitor V1 task.
  .github/CODEOWNERS
  Tasks/AzureMonitorV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureMonitorV0/task.json
  Tasks/AzureMonitorV0/task.loc.json
  Tasks/AzureMonitorV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureMonitorV1/icon.png
  Tasks/AzureMonitorV1/task.json
  Tasks/AzureMonitorV1/task.loc.json
  make-options.json
Labels: Area: Release

#9195 Updated documentation of OverwriteBehaviour input in ServiceFabricDeployV1
  Tasks/ServiceFabricDeployV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/ServiceFabricDeployV1/task.json
  Tasks/ServiceFabricDeployV1/task.loc.json
Labels: Area: Release

#9227 Users/suaggar/newtask text change
  Tasks/FileTransformV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/FileTransformV1/task.json
Labels: Area: AzureAppService, Area: Release

#9155 Fix git diff using merge-base
  ci/filter-tasks.js
Labels: Area: Core

#9236 Users/suaggar/newtask text change
  make-options.json
Labels: Area: Release

#9240 Removed multiselect option on 'resources' input. Added alertRule filter
  Tasks/AzureMonitorV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureMonitorV1/task.json
  Tasks/AzureMonitorV1/task.loc.json
Labels: Area: Release

#9039 Kubernetes Manifest based task
  Tasks/Common/utility-common/helm-object-model.ts
  Tasks/Common/utility-common/helmutility.ts
  Tasks/Common/utility-common/kubectl-object-model.ts
  Tasks/Common/utility-common/kubectlutility.ts
  Tasks/Common/utility-common/restutilities.ts
  Tasks/KubernetesManifestV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/KubernetesManifestV0/ThirdPartyNotices.txt
  Tasks/KubernetesManifestV0/icon.png
  Tasks/KubernetesManifestV0/make.json
  Tasks/KubernetesManifestV0/package-lock.json
  Tasks/KubernetesManifestV0/package.json
  Tasks/KubernetesManifestV0/src/actions/bake.ts
  Tasks/KubernetesManifestV0/src/actions/deploy.ts
  Tasks/KubernetesManifestV0/src/connection.ts
  Tasks/KubernetesManifestV0/src/run.ts
  Tasks/KubernetesManifestV0/src/utilities.ts
  Tasks/KubernetesManifestV0/task.json
  Tasks/KubernetesManifestV0/task.loc.json
  Tasks/KubernetesManifestV0/tsconfig.json
Labels: Area: Release

#9251 [Azure PowerShell V2 & V3] Set & Clear context at process Scope
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
  Tasks/AzureFileCopyV3/task.json
  Tasks/AzureFileCopyV3/task.loc.json
  Tasks/AzurePowerShellV2/task.json
  Tasks/AzurePowerShellV2/task.loc.json
  Tasks/AzurePowerShellV3/task.json
  Tasks/AzurePowerShellV3/task.loc.json
  Tasks/Common/VstsAzureHelpers_/InitializeAzureRMFunctions.ps1
  Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenSPAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Utility.ps1
Labels: Area: Release

#9296 Fixing the Bitbucket commit url in Jenkins task.
  Tasks/JenkinsDownloadArtifactsV1/ArtifactDetails/CommitsDownloader.ts
  Tasks/JenkinsDownloadArtifactsV1/Tests/L0.ts
  Tasks/JenkinsDownloadArtifactsV1/Tests/L0ValidateBitBucketCommitUrl.ts
  Tasks/JenkinsDownloadArtifactsV1/task.json
  Tasks/JenkinsDownloadArtifactsV1/task.loc.json
Labels: Area: Release

#9298 Fixing the Bitbucket commit url in Jenkins task.
  Tasks/JenkinsDownloadArtifactsV1/ArtifactDetails/CommitsDownloader.ts
  Tasks/JenkinsDownloadArtifactsV1/Tests/L0.ts
  Tasks/JenkinsDownloadArtifactsV1/Tests/L0ValidateBitBucketCommitUrl.ts
  Tasks/JenkinsDownloadArtifactsV1/task.json
  Tasks/JenkinsDownloadArtifactsV1/task.loc.json
Labels: Area: Release

#9294 Login to Azure RM at process scope & Clear context at process scope only
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
  Tasks/AzureFileCopyV3/task.json
  Tasks/AzureFileCopyV3/task.loc.json
  Tasks/AzurePowerShellV2/task.json
  Tasks/AzurePowerShellV2/task.loc.json
  Tasks/AzurePowerShellV3/task.json
  Tasks/AzurePowerShellV3/task.loc.json
  Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1
  Tasks/Common/VstsAzureHelpers_/Utility.ps1
Labels: Area: Release

#9320 Update README.md
  Tasks/AzureRmWebAppDeploymentV4/README.md
Labels: Area: Release

#9327 Azure PowerShell - Set Error Action to Stop for disconnect & clear context
  Tasks/AzurePowerShellV2/task.json
  Tasks/AzurePowerShellV2/task.loc.json
  Tasks/AzurePowerShellV3/task.json
  Tasks/AzurePowerShellV3/task.loc.json
  Tasks/Common/VstsAzureHelpers_/Utility.ps1
Labels: Area: Release

#9137 Updated output variable to use managed image location
  Tasks/PackerBuildV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/PackerBuildV1/src/constants.ts
  Tasks/PackerBuildV1/src/operations/packerBuild.ts
  Tasks/PackerBuildV1/src/taskParameters.ts
  Tasks/PackerBuildV1/task.json
  Tasks/PackerBuildV1/task.loc.json
Labels: Area: Release

#9333 Azure PowerShell - Set Error Action to Stop for disconnect & clear context (M146)
  Tasks/AzurePowerShellV2/task.json
  Tasks/AzurePowerShellV2/task.loc.json
  Tasks/AzurePowerShellV3/task.json
  Tasks/AzurePowerShellV3/task.loc.json
  Tasks/Common/VstsAzureHelpers_/Utility.ps1
Labels: Area: Release

#9349 Azure PS - Change Error Action to Stop
  Tasks/AzurePowerShellV3/task.json
  Tasks/AzurePowerShellV3/task.loc.json
  Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1
Labels: Area: Release

#9337 Azure PowerShell - Clear context at process level
  Tasks/AzurePowerShellV2/task.json
  Tasks/AzurePowerShellV2/task.loc.json
  Tasks/AzurePowerShellV3/task.json
  Tasks/AzurePowerShellV3/task.loc.json
  Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1
Labels: Area: Release

#9368 change case in task folder name
  Tasks/DownloadGitHubReleasesV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DownloadGitHubReleasesV0/ThirdPartyNotices.txt
  Tasks/DownloadGitHubReleasesV0/githubreleases.handlebars.txt
  Tasks/DownloadGitHubReleasesV0/icon.png
  Tasks/DownloadGitHubReleasesV0/icon.svg
  Tasks/DownloadGitHubReleasesV0/main.ts
  Tasks/DownloadGitHubReleasesV0/package-lock.json
  Tasks/DownloadGitHubReleasesV0/package.json
  Tasks/DownloadGitHubReleasesV0/task.json
  Tasks/DownloadGitHubReleasesV0/task.loc.json
  Tasks/DownloadGitHubReleasesV0/tsconfig.json
  Tasks/DownloadGitHubReleasesV0/typings.json
Labels: Area: Release

#9367 change case in task folder name
  Tasks/DownloadGitHubReleasesV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DownloadGitHubReleasesV0/ThirdPartyNotices.txt
  Tasks/DownloadGitHubReleasesV0/githubreleases.handlebars.txt
  Tasks/DownloadGitHubReleasesV0/icon.png
  Tasks/DownloadGitHubReleasesV0/icon.svg
  Tasks/DownloadGitHubReleasesV0/main.ts
  Tasks/DownloadGitHubReleasesV0/package-lock.json
  Tasks/DownloadGitHubReleasesV0/package.json
  Tasks/DownloadGitHubReleasesV0/task.json
  Tasks/DownloadGitHubReleasesV0/task.loc.json
  Tasks/DownloadGitHubReleasesV0/tsconfig.json
  Tasks/DownloadGitHubReleasesV0/typings.json
Labels: Area: Release

#9373 update artifact-engine version
  Tasks/DownloadBuildArtifactsV0/package-lock.json
  Tasks/DownloadBuildArtifactsV0/package.json
Labels: Area: Release

#9360 Users/ajya/sql server module import m146
  Tasks/SqlAzureDacpacDeploymentV1/SqlAzureActions.ps1
  Tasks/SqlAzureDacpacDeploymentV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/SqlAzureDacpacDeploymentV1/Utility.ps1
  Tasks/SqlAzureDacpacDeploymentV1/task.json
  Tasks/SqlAzureDacpacDeploymentV1/task.loc.json
Labels: Area: Release

#9371 Modifying metadata pushed by app service deploy task
  Tasks/AzureRmWebAppDeploymentV3/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/operations/AzureAppServiceUtility.ts
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/AzureRmDeploy-common/operations/AzureAppServiceUtility.ts
Labels: Area: AzureAppService, Area: Release

#9326 Add support for AzureChinaCloud
  Tasks/AzureIoTEdgeV2/deployimage.ts
  Tasks/AzureIoTEdgeV2/task.json
  Tasks/AzureIoTEdgeV2/task.loc.json
  Tasks/AzureIoTEdgeV2/telemetry.ts
Labels: Area: Release

#9339 docker task changes
  Tasks/DockerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
Labels: Area: Release

#9402 bump up artifact-engine version in tasks
  Tasks/DownloadFileshareArtifactsV0/package.json
  Tasks/DownloadFileshareArtifactsV0/task.json
  Tasks/DownloadFileshareArtifactsV0/task.loc.json
  Tasks/DownloadGitHubReleasesV0/package.json
  Tasks/DownloadGitHubReleasesV0/task.json
  Tasks/DownloadGitHubReleasesV0/task.loc.json
  Tasks/JenkinsDownloadArtifactsV1/package.json
  Tasks/JenkinsDownloadArtifactsV1/task.loc.json
Labels: Area: Release

#9338 File Transform - JSON variable substitution - Support all types
  Tasks/AzureRmWebAppDeploymentV4/Tests/L0.ts
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/webdeployment-common/Tests/L1JsonVarSubV2.ts
  Tasks/Common/webdeployment-common/fileTransformationsUtility.ts
  Tasks/Common/webdeployment-common/jsonvariablesubstitutionutility.ts
  Tasks/FileTransformV1/package-lock.json
  Tasks/FileTransformV1/task.json
  Tasks/FileTransformV1/task.loc.json
Labels: Area: AzureAppService, Area: Release

#9387 .netcoreinstaller improve error message when versionfile malformed
  Tasks/DotNetCoreInstallerV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DotNetCoreInstallerV0/releasesfetcher.ts
  Tasks/DotNetCoreInstallerV0/task.json
  Tasks/DotNetCoreInstallerV0/task.loc.json
Labels: Area: Release

#9395 ARG task log deployment name
  Tasks/AzureResourceGroupDeploymentV2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureResourceGroupDeploymentV2/operations/ResourceGroup.ts
  Tasks/AzureResourceGroupDeploymentV2/task.json
  Tasks/AzureResourceGroupDeploymentV2/task.loc.json
  Tasks/Common/azure-arm-rest/AzureServiceClient.ts
Labels: Area: Release

#9358 Adding dockercli installer task in task list
  make-options.json
Labels: Area: Release

#9444 [Docker] Qualifying image name before tagging
  Tasks/DockerV0/containerbuild.ts
  Tasks/DockerV0/task.json
  Tasks/DockerV0/task.loc.json
  Tasks/DockerV1/containerbuild.ts
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
Labels: Area: Release

#9468 Adding Readme file for the Download Github Releases Task.
  Tasks/DownloadGitHubReleasesV0/README.md
Labels: Area: Release
