Repository microsoft/azure-pipelines-tasks, pull requests merged in 2019-02, with the labels that each got.

#9464 Kubernetes Manifest based task - Delete action added
  Tasks/Common/utility-common/kubectl-object-model.ts
  Tasks/KubernetesManifestV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/KubernetesManifestV0/src/actions/delete.ts
  Tasks/KubernetesManifestV0/src/models/TaskInputParameters.ts
  Tasks/KubernetesManifestV0/src/run.ts
  Tasks/KubernetesManifestV0/task.json
  Tasks/KubernetesManifestV0/task.loc.json
Labels: Area: Release

#9481 rename DownloadGitHubReleases task
  Tasks/DownloadGitHubReleaseV0/README.md
  Tasks/DownloadGitHubReleaseV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DownloadGitHubReleaseV0/ThirdPartyNotices.txt
  Tasks/DownloadGitHubReleaseV0/githubrelease.handlebars.txt
  Tasks/DownloadGitHubReleaseV0/icon.png
  Tasks/DownloadGitHubReleaseV0/icon.svg
  Tasks/DownloadGitHubReleaseV0/main.ts
  Tasks/DownloadGitHubReleaseV0/package-lock.json
  Tasks/DownloadGitHubReleaseV0/package.json
  Tasks/DownloadGitHubReleaseV0/task.json
  Tasks/DownloadGitHubReleaseV0/task.loc.json
  Tasks/DownloadGitHubReleaseV0/tsconfig.json
  Tasks/DownloadGitHubReleaseV0/typings.json
  make-options.json
Labels: Area: Release

#9531 Microsoft/users/raagra/iis manage fix empty password
  Tasks/IISWebAppManagementOnMachineGroupV0/Utility.ps1
  Tasks/IISWebAppManagementOnMachineGroupV0/task.json
  Tasks/IISWebAppManagementOnMachineGroupV0/task.loc.json
Labels: Area: Release

#9513 Adding Session Id support in Publish to service bus task
  Tasks/PublishToAzureServiceBusV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/PublishToAzureServiceBusV1/task.json
  Tasks/PublishToAzureServiceBusV1/task.loc.json
Labels: Area: Release

#6560 Ignore source paths with invalid path characters
  Tasks/PublishSymbolsV2/IndexHelpers/SourceFileFunctions.ps1
  Tasks/PublishSymbolsV2/Tests/Get-SourceFilePaths.WarnsForSourceFileNotFound.ps1
Labels: Area: Symbols

#9551 Azure Web Ap & Function App -Port Affinity issue fix
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#9521 This adds the support for repo search in github related tasks
  Tasks/DownloadBuildArtifactsV0/task.json
  Tasks/DownloadBuildArtifactsV0/task.loc.json
  Tasks/DownloadGitHubReleaseV0/task.json
  Tasks/DownloadGitHubReleaseV0/task.loc.json
  Tasks/GitHubReleaseV0/task.json
  Tasks/GitHubReleaseV0/task.loc.json
Labels: Area: Release

#9525 Fix smart quotes in docs on publishTestResults in DotNetCoreCLIv2
  Tasks/DotNetCoreCLIV2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
Labels: Area: Release

#9590 Fix smart quotes in docs on publishTestResults in DotNetCoreCLIv2 (#9…
  Tasks/DotNetCoreCLIV2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
Labels: Area: Release

#9641 App Service Kudu - reuse affinity cookie for deployment
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureRmWebAppDeploymentV3/package-lock.json
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/package-lock.json
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#9642 App Service - reuse kudu affinity cookie M148
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureRmWebAppDeploymentV3/package-lock.json
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/package-lock.json
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#9643 App Service - reuse kudu affinity cookie M147
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureRmWebAppDeploymentV3/package-lock.json
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/package-lock.json
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service-kudu.ts
  Tasks/Common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#9625 Updating the version to update the package
  Tasks/DotNetCoreCLIV2/package-lock.json
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
Labels: Area: Release

#9624 Updating the task version to reflect the help text update
  Tasks/DotNetCoreCLIV2/package-lock.json
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
Labels: Area: Release

#9600 Fix for AzureWebAppContainerV1: Can't select a slot to deploy
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
Labels: Area: AzureAppService, Area: Release

#9632 Show environment variables in the Azure CLI task.
  Tasks/AzureCLIV1/task.json
  Tasks/AzureCLIV1/task.loc.json
Labels: Area: Release

#9679 null fix in xdt logic
  Tasks/Common/webdeployment-common/xdttransformationutility.ts
  Tasks/FileTransformV1/task.json
  Tasks/FileTransformV1/task.loc.json
Labels: Area: Release, FileTransforms

#9680 null fix in xdt logic (#9679)
  Tasks/Common/webdeployment-common/xdttransformationutility.ts
  Tasks/FileTransformV1/task.json
  Tasks/FileTransformV1/task.loc.json
Labels: Area: Release, FileTransforms
