Repository microsoft/azure-pipelines-tasks, pull requests merged in 2019-04, with the labels that each got.

#10007 File Transform bug fix to compute multiple transform rules
  Tasks/AzureMysqlDeploymentV1/task.json
  Tasks/AzureMysqlDeploymentV1/task.loc.json
  Tasks/AzureRmWebAppDeploymentV3/task.json
  Tasks/AzureRmWebAppDeploymentV3/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/Common/webdeployment-common/fileTransformationsUtility.ts
  Tasks/FileTransformV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/FileTransformV1/task.json
  Tasks/IISWebAppDeploymentOnMachineGroupV0/task.json
  Tasks/IISWebAppDeploymentOnMachineGroupV0/task.loc.json
  Tasks/MysqlDeploymentOnMachineGroupV1/task.json
  Tasks/MysqlDeploymentOnMachineGroupV1/task.loc.json
Labels: Area: Release

#10012 Azure web app - Zip utility fix
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/webdeployment-common/ziputility.ts
Labels: Area: AzureAppService, Area: Release

#10033 Azure function app - consumption app deploy YAML fix
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureFunctionAppV1/taskparameters.ts
Labels: Area: AzureAppService, Area: Release

#10034 Azure web app - Zip utility fix (m150)
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/webdeployment-common/ziputility.ts
Labels: Area: AzureAppService, Area: Release

#9943 Azure web app - support multicontainer
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppContainerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureWebAppContainerV1/Tests/utils.ts
  Tasks/AzureWebAppContainerV1/package-lock.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppContainerV1/taskparameters.ts
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/operations/ContainerBasedDeploymentUtility.ts
  Tasks/Common/AzureRmDeploy-common/webdeployment-common/utility.ts
Labels: Area: AzureAppService, Area: Release

#10113 Make Azure App service tasks GA
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
Labels: Area: AzureAppService, Area: Release

#10120 Fixed typos in task "azurewebapp"
  Tasks/AzureWebAppV1/azurermwebappdeployment.ts
  Tasks/AzureWebAppV1/deploymentProvider/DeploymentFactory.ts
Labels: Area: AzureAppService, Area: Release

#9848 Add "silently continue" to mysql command location
  Tasks/AzureMysqlDeploymentV1/Window-MysqlCli-Installer.ps1
Labels: Area: Release

#9956 Add extra options to dotnet pack command
  Tasks/DotNetCoreCLIV2/README.md
  Tasks/DotNetCoreCLIV2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DotNetCoreCLIV2/packcommand.ts
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
Labels: Area: Artifacts

#10168 Azure App Service tasks - Make GA
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
Labels: Area: AzureAppService, Area: Release

#10171 Azure Web app container task - helptext update for startup command.
  Tasks/AzureFunctionAppContainerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
  Tasks/AzureWebAppContainerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
Labels: Area: AzureAppService, Area: Release

#10134 Using Generate-AzureStorageContainerSASToken from Utils instead of Ne…
  Tasks/AzureFileCopyV3/AzureFileCopy.ps1
Labels: Area: Release

#10250 Empty input string issue fix
  Tasks/SqlDacpacDeploymentOnMachineGroupV0/Utility.ps1
  Tasks/SqlDacpacDeploymentOnMachineGroupV0/task.json
  Tasks/SqlDacpacDeploymentOnMachineGroupV0/task.loc.json
Labels: Area: Release

#10245 Add assignees for "Release" issues
  issue-rules.yml
Labels: Area: Release

#10243 fix wrong osTypeMap (kind) value for Windows container
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppContainerV1/taskparameters.ts
Labels: Area: AzureAppService, Area: Release

#10252 Azure App Service Deploy - help markdown update for Publish profile
  Tasks/AzureRmWebAppDeploymentV4/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureRmWebAppDeploymentV4/task.json
  Tasks/AzureRmWebAppDeploymentV4/task.loc.json
Labels: Area: AzureAppService, Area: Release
