Repository microsoft/azure-pipelines-tasks, pull requests merged in 2019-03, with the labels that each got.

#9703 Added support for proxy in AFC v3
  Tasks/AzureFileCopyV3/task.json
  Tasks/AzureFileCopyV3/task.loc.json
  Tasks/Common/VstsAzureHelpers_/Tests/Get-MsiAccessTokenTests.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.AzurePreferredFallsBack.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.AzureRMPreferredFallsBack.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.BothPreferredFallsBack.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.ThrowsWhenNotFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-AzureModule.ValidatesClassicVersion.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ImportsModules.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ReturnsFalseWhenNotFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromModulePath.ValidatesRMProfileFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromSdkPath.ImportsModule.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Import-FromSdkPath.ReturnsFalseWhenNotFound.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-Azure.PassesInputs.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-Azure.ThrowsWhenServiceNameIsNull.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ManagedServiceIdentity.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenAzureStackSPAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenCertAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenCertAuthAndEnvironment.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenSPAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenSPNCertAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenSPNCertAuthWithAZ.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.PassesValuesWhenUPAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsUsefulErrorWhenSPAuthAndAddAccountFails.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsUsefulErrorWhenUPAuthAndAddAccountFails.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsWhenRMAndCertAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsWhenSPAuthAndClassic099.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Initialize-AzureSubscription.ThrowsWhenUnsupportedAuth.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/OverriddesGlobalDebugPreference.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Set-CurrentAzureRMSubscription.PassesValues.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Set-CurrentAzureSubscription.PassesValues.ps1
  Tasks/Common/VstsAzureHelpers_/Tests/Set-UserAgent.PassesValues.ps1
  Tasks/Common/VstsAzureHelpers_/VstsAzureHelpers_.psm1
  Tasks/Common/VstsAzureRestHelpers_/VstsAzureRestHelpers_.psm1
Labels: Area: Release

#9550 Azure App Service - Fix JS Heap out of memory
  Tasks/AzureFunctionAppV1/package-lock.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppV1/package-lock.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/package-lock.json
  Tasks/Common/AzureRmDeploy-common/package.json
  Tasks/Common/AzureRmDeploy-common/webdeployment-common/packageUtility.ts
  Tasks/Common/AzureRmDeploy-common/webdeployment-common/ziputility.ts
Labels: Area: AzureAppService, Area: Release

#9724 Check for consumption plan
  Tasks/AzureFunctionAppV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFunctionAppV1/deploymentProvider/AzureRmWebAppDeploymentProvider.ts
  Tasks/AzureFunctionAppV1/deploymentProvider/ConsumptionWebAppDeploymentProvider.ts
  Tasks/AzureFunctionAppV1/deploymentProvider/DeploymentFactory.ts
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureFunctionAppV1/taskparameters.ts
Labels: Area: AzureAppService, Area: Release

#9726 Packer Build V1: Fail fast if VHD source is specified for generating managed image
  Tasks/PackerBuildV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/PackerBuildV1/src/taskParameters.ts
  Tasks/PackerBuildV1/task.json
  Tasks/PackerBuildV1/task.loc.json
Labels: Area: Release

#9738 updated the logic to get released versions of kubectl
  Tasks/AzureIoTEdgeV2/task.json
  Tasks/AzureIoTEdgeV2/task.loc.json
  Tasks/AzureMysqlDeploymentV1/task.json
  Tasks/AzureMysqlDeploymentV1/task.loc.json
  Tasks/AzureVmssDeploymentV0/task.json
  Tasks/AzureVmssDeploymentV0/task.loc.json
  Tasks/Common/utility-common/kubectlutility.ts
  Tasks/DotNetCoreCLIV2/task.json
  Tasks/DotNetCoreCLIV2/task.loc.json
  Tasks/DownloadPackageV0/task.json
  Tasks/DownloadPackageV0/task.loc.json
  Tasks/DownloadPackageV1/task.json
  Tasks/DownloadPackageV1/task.loc.json
  Tasks/GitHubReleaseV0/task.json
  Tasks/GitHubReleaseV0/task.loc.json
  Tasks/GradleV2/task.json
  Tasks/GradleV2/task.loc.json
  Tasks/HelmDeployV0/task.json
  Tasks/HelmDeployV0/task.loc.json
  Tasks/HelmInstallerV0/task.json
  Tasks/HelmInstallerV0/task.loc.json
  Tasks/KubernetesV0/task.json
  Tasks/KubernetesV0/task.loc.json
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
  Tasks/NpmV1/task.json
  Tasks/NpmV1/task.loc.json
  Tasks/NuGetCommandV2/task.json
  Tasks/NuGetCommandV2/task.loc.json
  Tasks/NuGetPublisherV0/task.json
  Tasks/NuGetPublisherV0/task.loc.json
  Tasks/NuGetV0/task.json
  Tasks/NuGetV0/task.loc.json
  Tasks/PipAuthenticateV0/task.json
  Tasks/PipAuthenticateV0/task.loc.json
  Tasks/TwineAuthenticateV0/task.json
  Tasks/TwineAuthenticateV0/task.loc.json
  Tasks/UniversalPackagesV0/task.json
  Tasks/UniversalPackagesV0/task.loc.json
Labels: Area: Release

#9744 inputs error handling for yaml flow
  Tasks/GitHubReleaseV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/GitHubReleaseV0/main.ts
  Tasks/GitHubReleaseV0/operations/Action.ts
  Tasks/GitHubReleaseV0/operations/Helper.ts
  Tasks/GitHubReleaseV0/operations/Utility.ts
  Tasks/GitHubReleaseV0/task.json
  Tasks/GitHubReleaseV0/task.loc.json
Labels: Area: Release

#9287 Added DuffleToolInstaller Task
  .github/CODEOWNERS
  Tasks/DuffleInstallerV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DuffleInstallerV0/ThirdPartyNotices.txt
  Tasks/DuffleInstallerV0/icon.png
  Tasks/DuffleInstallerV0/make.json
  Tasks/DuffleInstallerV0/package.json
  Tasks/DuffleInstallerV0/src/duffle.ts
  Tasks/DuffleInstallerV0/src/duffleinstaller.ts
  Tasks/DuffleInstallerV0/task.json
  Tasks/DuffleInstallerV0/task.loc.json
  Tasks/DuffleInstallerV0/tsconfig.json
Labels: Area: Release

#9740 Modifying the logic of uploading assets for proper log statements
  Tasks/GitHubReleaseV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/GitHubReleaseV0/Tests/ActionTests.ts
  Tasks/GitHubReleaseV0/Tests/CreateAction2L0Tests.ts
  Tasks/GitHubReleaseV0/Tests/CreateActionL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/DeleteAction2L0Tests.ts
  Tasks/GitHubReleaseV0/Tests/DeleteActionL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/EditAction2L0Tests.ts
  Tasks/GitHubReleaseV0/Tests/EditActionL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/HelperL0Tests.ts
  Tasks/GitHubReleaseV0/Tests/HelperTests.ts
  Tasks/GitHubReleaseV0/Tests/L0.ts
  Tasks/GitHubReleaseV0/main.ts
  Tasks/GitHubReleaseV0/operations/Action.ts
  Tasks/GitHubReleaseV0/operations/ChangeLog.ts
  Tasks/GitHubReleaseV0/operations/Helper.ts
  Tasks/GitHubReleaseV0/operations/Utility.ts
  Tasks/GitHubReleaseV0/task.json
  Tasks/GitHubReleaseV0/task.loc.json
Labels: Area: Release

#9786 Use agent's temp directory instead of OS's.
  Tasks/PackerBuildV0/src/utilities.ts
  Tasks/PackerBuildV0/task.json
  Tasks/PackerBuildV0/task.loc.json
  Tasks/PackerBuildV1/src/utilities.ts
  Tasks/PackerBuildV1/task.json
  Tasks/PackerBuildV1/task.loc.json
Labels: Area: Release

#9763 [Azure Function App] Uploading package and generating SAS URL
  Tasks/AzureFunctionAppV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFunctionAppV1/deploymentProvider/ConsumptionWebAppDeploymentProvider.ts
  Tasks/AzureFunctionAppV1/package-lock.json
  Tasks/AzureFunctionAppV1/package.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service.ts
Labels: Area: AzureAppService, Area: Release

#9707 Adding Docker V2 task - Simplify the task inputs for YAML
  Tasks/Common/docker-common/containerconnection.ts
  Tasks/Common/docker-common/dockercommandutils.ts
  Tasks/Common/docker-common/fileutils.ts
  Tasks/Common/docker-common/pipelineutils.ts
  Tasks/Common/docker-common/registryauthenticationprovider/registryauthenticationtoken.ts
  Tasks/DockerComposeV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerComposeV0/dockercomposeconnection.ts
  Tasks/DockerComposeV0/task.json
  Tasks/DockerComposeV0/task.loc.json
  Tasks/DockerV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerV0/containerbuild.ts
  Tasks/DockerV0/containerrun.ts
  Tasks/DockerV0/task.json
  Tasks/DockerV0/task.loc.json
  Tasks/DockerV0/utils.ts
  Tasks/DockerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerV1/containerbuild.ts
  Tasks/DockerV1/containerrun.ts
  Tasks/DockerV1/task.json
  Tasks/DockerV1/task.loc.json
  Tasks/DockerV1/utils.ts
  Tasks/DockerV2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DockerV2/docker.ts
  Tasks/DockerV2/dockerbuild.ts
  Tasks/DockerV2/dockerbuildandpush.ts
  Tasks/DockerV2/dockercommand.ts
  Tasks/DockerV2/dockerlogin.ts
  Tasks/DockerV2/dockerlogout.ts
  Tasks/DockerV2/dockerpush.ts
  Tasks/DockerV2/icon.png
  Tasks/DockerV2/make.json
  Tasks/DockerV2/package-lock.json
  Tasks/DockerV2/package.json
  Tasks/DockerV2/task.json
  Tasks/DockerV2/task.loc.json
  Tasks/DockerV2/tsconfig.json
  Tasks/DockerV2/utils.ts
  Tasks/KubernetesV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/KubernetesV0/task.json
  Tasks/KubernetesV0/task.loc.json
  Tasks/KubernetesV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/KubernetesV1/task.json
  Tasks/KubernetesV1/task.loc.json
Labels: Area: Release

#9806 Added task option to pass a test run title when publishing test results
  Tasks/DotNetCoreCLIV2/dotnetcore.ts
  Tasks/DotNetCoreCLIV2/task.json
Labels: Area: Test

#9814 Logging repository name in telemetry
  Tasks/GitHubReleaseV0/operations/Helper.ts
  Tasks/GitHubReleaseV0/task.json
  Tasks/GitHubReleaseV0/task.loc.json
Labels: Area: Release

#9856 Re-enable app service tests
  Tasks/AzureFunctionAppContainerV1/Tests/L0.ts
  Tasks/AzureRmWebAppDeploymentV3/Tests/L0.ts
  Tasks/AzureRmWebAppDeploymentV4/Tests/L0.ts
  Tasks/AzureWebAppContainerV1/Tests/L0.ts
  ci/build-all-steps.yml
Labels: Area: AzureAppService

#9819 Restart Web App Container after config update
  Tasks/AzureFunctionAppContainerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFunctionAppContainerV1/Tests/L0.ts
  Tasks/AzureFunctionAppContainerV1/Tests/mock_utils.ts
  Tasks/AzureFunctionAppContainerV1/Tests/utils.ts
  Tasks/AzureFunctionAppContainerV1/azurefunctiononcontainerprovider.ts
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppContainerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureWebAppContainerV1/Tests/L0.ts
  Tasks/AzureWebAppContainerV1/Tests/mock_utils.ts
  Tasks/AzureWebAppContainerV1/Tests/utils.ts
  Tasks/AzureWebAppContainerV1/azurermwebappdeploymentprovider.ts
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/operations/ContainerBasedDeploymentUtility.ts
Labels: Area: AzureAppService, Area: Release

#9729 Added task.json and taskdesign.md for new version of DotNetCoreInstal…
  .github/CODEOWNERS
  Tasks/DotNetCoreInstallerV0/task.json
  Tasks/DotNetCoreInstallerV1/README.md
  Tasks/DotNetCoreInstallerV1/Strings/resources.resjson/de-de/resources.resjson
  Tasks/DotNetCoreInstallerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DotNetCoreInstallerV1/Strings/resources.resjson/es-es/resources.resjson
  Tasks/DotNetCoreInstallerV1/Strings/resources.resjson/fr-fr/resources.resjson
  Tasks/DotNetCoreInstallerV1/Strings/resources.resjson/it-IT/resources.resjson
  Tasks/DotNetCoreInstallerV1/Strings/resources.resjson/ja-jp/resources.resjson
  Tasks/DotNetCoreInstallerV1/Strings/resources.resjson/ko-KR/resources.resjson
  Tasks/DotNetCoreInstallerV1/Strings/resources.resjson/ru-RU/resources.resjson
  Tasks/DotNetCoreInstallerV1/Strings/resources.resjson/zh-CN/resources.resjson
  Tasks/DotNetCoreInstallerV1/Strings/resources.resjson/zh-TW/resources.resjson
  Tasks/DotNetCoreInstallerV1/Task Design.md
  Tasks/DotNetCoreInstallerV1/Tests/L0.ts
  Tasks/DotNetCoreInstallerV1/Tests/mocks/mockedModels.ts
  Tasks/DotNetCoreInstallerV1/Tests/modelsChannelTests.ts
  Tasks/DotNetCoreInstallerV1/Tests/modelsGetRuntimeVersionTests.ts
  Tasks/DotNetCoreInstallerV1/Tests/modelsVersionPartsTests.ts
  Tasks/DotNetCoreInstallerV1/Tests/package-lock.json
  Tasks/DotNetCoreInstallerV1/Tests/package.json
  Tasks/DotNetCoreInstallerV1/Tests/versionFetcherGetDownloadUrlFailTests.ts
  Tasks/DotNetCoreInstallerV1/Tests/versionFetcherGetVersionInfoFailTests.ts
  Tasks/DotNetCoreInstallerV1/Tests/versionFetcherGetVersionInfoTestsCorrect.ts
  Tasks/DotNetCoreInstallerV1/Tests/versionUtilityChannelVersionCompareTests.ts
  Tasks/DotNetCoreInstallerV1/Tests/versionUtilityGetMatchingVersionFromListTests.ts
  Tasks/DotNetCoreInstallerV1/Tests/versionUtilityVersionCompareTests.ts
  Tasks/DotNetCoreInstallerV1/ThirdPartyNotices.txt
  Tasks/DotNetCoreInstallerV1/dotnetcoreinstaller.ts
  Tasks/DotNetCoreInstallerV1/externals/get-os-distro.sh
  Tasks/DotNetCoreInstallerV1/externals/get-os-platform.ps1
  Tasks/DotNetCoreInstallerV1/icon.png
  Tasks/DotNetCoreInstallerV1/icon.svg
  Tasks/DotNetCoreInstallerV1/make.json
  Tasks/DotNetCoreInstallerV1/models.ts
  Tasks/DotNetCoreInstallerV1/package-lock.json
  Tasks/DotNetCoreInstallerV1/package.json
  Tasks/DotNetCoreInstallerV1/task.json
  Tasks/DotNetCoreInstallerV1/task.loc.json
  Tasks/DotNetCoreInstallerV1/tsconfig.json
  Tasks/DotNetCoreInstallerV1/versionfetcher.ts
  Tasks/DotNetCoreInstallerV1/versioninstaller.ts
  Tasks/DotNetCoreInstallerV1/versionutilities.ts
  make-options.json
Labels: Area: Release

#9877 Correctly detect directories and files in GitHub Release task
  Tasks/GitHubReleaseV0/operations/Utility.ts
Labels: Area: Release

#9818 Azure Functions - Support Linux consumption app deployment
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFunctionAppV1/deploymentProvider/AzureRmWebAppDeploymentProvider.ts
  Tasks/AzureFunctionAppV1/deploymentProvider/ConsumptionWebAppDeploymentProvider.ts
  Tasks/AzureFunctionAppV1/deploymentProvider/DeploymentFactory.ts
  Tasks/AzureFunctionAppV1/package-lock.json
  Tasks/AzureFunctionAppV1/package.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureFunctionAppV1/taskparameters.ts
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service.ts
Labels: Area: AzureAppService, Area: Release

#9895 Retry for update deployment status
  Tasks/AzureFunctionAppContainerV1/task.json
  Tasks/AzureFunctionAppContainerV1/task.loc.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppV1/task.json
  Tasks/AzureWebAppV1/task.loc.json
  Tasks/Common/AzureRmDeploy-common/azure-arm-rest/azure-arm-app-service-kudu.ts
Labels: Area: AzureAppService, Area: Release

#9899 Azure App Service tasks - reduce time in L0 tests
  Tasks/Common/AzureRmDeploy-common/Tests/L0-azure-arm-app-service.ts
  Tasks/Common/AzureRmDeploy-common/Tests/L0-azure-arm-appinsights-tests.ts
  Tasks/Common/AzureRmDeploy-common/Tests/mock_utils.ts
  Tasks/Common/azure-arm-rest/Tests/L0-azure-arm-app-service.ts
  Tasks/Common/azure-arm-rest/Tests/L0-azure-arm-appinsights-tests.ts
  Tasks/Common/azure-arm-rest/Tests/mock_utils.ts
Labels: Area: Release

#9846 Improving failure message for AzureCLI task
  Tasks/AzureCLIV1/azureclitask.ts
  Tasks/AzureCLIV1/task.json
  Tasks/AzureCLIV1/task.loc.json
Labels: Area: Release

#9898 Improve Download GHR task
  Tasks/DownloadGitHubReleaseV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/DownloadGitHubReleaseV0/main.ts
  Tasks/DownloadGitHubReleaseV0/package-lock.json
  Tasks/DownloadGitHubReleaseV0/task.json
  Tasks/DownloadGitHubReleaseV0/task.loc.json
Labels: Area: Release

#9952 Azure Web app for containers - remove os type input
  Tasks/AzureWebAppContainerV1/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureWebAppContainerV1/task.json
  Tasks/AzureWebAppContainerV1/task.loc.json
  Tasks/AzureWebAppContainerV1/taskparameters.ts
Labels: Area: AzureAppService, Area: Release

#9953 FileTransform - make file type dropdown not editable
  Tasks/FileTransformV1/task.json
  Tasks/FileTransformV1/task.loc.json
Labels: Area: Release
