Repository microsoft/azure-pipelines-tasks, pull requests merged in 2022-01, with the labels that each got.

#15614 Add minimumAgentVersion to migrateNode10.md
  docs/migrateNode10.md
Labels: documentation

#15672 Remove ACRTaskV0
  .github/CODEOWNERS
  Tasks/ACRTaskV0/Strings/resources.resjson/de-DE/resources.resjson
  Tasks/ACRTaskV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/ACRTaskV0/Strings/resources.resjson/es-ES/resources.resjson
  Tasks/ACRTaskV0/Strings/resources.resjson/fr-FR/resources.resjson
  Tasks/ACRTaskV0/Strings/resources.resjson/it-IT/resources.resjson
  Tasks/ACRTaskV0/Strings/resources.resjson/ja-JP/resources.resjson
  Tasks/ACRTaskV0/Strings/resources.resjson/ko-KR/resources.resjson
  Tasks/ACRTaskV0/Strings/resources.resjson/ru-RU/resources.resjson
  Tasks/ACRTaskV0/Strings/resources.resjson/zh-CN/resources.resjson
  Tasks/ACRTaskV0/Strings/resources.resjson/zh-TW/resources.resjson
  Tasks/ACRTaskV0/Tests/L0.ts
  Tasks/ACRTaskV0/Tests/TestStrings.ts
  Tasks/ACRTaskV0/Tests/UtilityL0Tests.ts
  Tasks/ACRTaskV0/icon.png
  Tasks/ACRTaskV0/icon.svg
  Tasks/ACRTaskV0/main.ts
  Tasks/ACRTaskV0/make.json
  Tasks/ACRTaskV0/models/acrtaskparameters.ts
  Tasks/ACRTaskV0/models/acrtaskrequestbody.ts
  Tasks/ACRTaskV0/operations/acrtaskclient.ts
  Tasks/ACRTaskV0/operations/acrtaskoperations.ts
  Tasks/ACRTaskV0/operations/azure-blob-upload-helper.ts
  Tasks/ACRTaskV0/package-lock.json
  Tasks/ACRTaskV0/package.json
  Tasks/ACRTaskV0/task.json
  Tasks/ACRTaskV0/task.loc.json
  Tasks/ACRTaskV0/tsconfig.json
  Tasks/ACRTaskV0/utilities/utils.ts
  make-options.json
Labels: enhancement

#15674 Remove ACRTaskV0 from localization
  Localize/LocProject.json
Labels: enhancement

#15844 [MavenV2 / MavenV3] Add `JAVA 17` to the JDK picklist
  Tasks/MavenV2/task.json
  Tasks/MavenV2/task.loc.json
  Tasks/MavenV3/task.json
  Tasks/MavenV3/task.loc.json
Labels: enhancement, Task: Maven
