Repository microsoft/azure-pipelines-tasks, pull requests merged in 2022-09, with the labels that each got.

#16866 Fixed task version for PR #16835
  Tasks/NodeToolV0/task.json
  Tasks/NodeToolV0/task.loc.json
Labels: Task: Npm

#15968 Migrate ContainerStructureTest task to Node10
  Tasks/ContainerStructureTestV0/Tests/L0.ts
  Tasks/ContainerStructureTestV0/containerstructuretest.ts
  Tasks/ContainerStructureTestV0/make.json
  Tasks/ContainerStructureTestV0/package-lock.json
  Tasks/ContainerStructureTestV0/package.json
  Tasks/ContainerStructureTestV0/task.json
  Tasks/ContainerStructureTestV0/task.loc.json
  Tasks/ContainerStructureTestV0/testresultspublisher.ts
  Tasks/ContainerStructureTestV0/testrunner.ts
Labels: enhancement

#16940 Update node16 migration guide
  docs/migrateNode16.md
Labels: documentation
