Repository microsoft/azure-pipelines-tasks, pull requests merged in 2022-02, with the labels that each got.

#15594 15070 #Azure File Copy Task 4.*: Update to AzCopy 10.11 to support cu…
  Tasks/AzureFileCopyV5/AzureFileCopy.ps1
  Tasks/AzureFileCopyV5/AzureFileCopyRemoteJob.ps1
  Tasks/AzureFileCopyV5/AzureUtilityARM.ps1
  Tasks/AzureFileCopyV5/AzureUtilityAz1.0.ps1
  Tasks/AzureFileCopyV5/AzureUtilityRest.ps1
  Tasks/AzureFileCopyV5/MimeMapping.json
  Tasks/AzureFileCopyV5/README.md
  Tasks/AzureFileCopyV5/Strings/resources.resjson/de-DE/resources.resjson
  Tasks/AzureFileCopyV5/Strings/resources.resjson/en-US/resources.resjson
  Tasks/AzureFileCopyV5/Strings/resources.resjson/es-ES/resources.resjson
  Tasks/AzureFileCopyV5/Strings/resources.resjson/fr-FR/resources.resjson
  Tasks/AzureFileCopyV5/Strings/resources.resjson/it-IT/resources.resjson
  Tasks/AzureFileCopyV5/Strings/resources.resjson/ja-JP/resources.resjson
  Tasks/AzureFileCopyV5/Strings/resources.resjson/ko-KR/resources.resjson
  Tasks/AzureFileCopyV5/Strings/resources.resjson/ru-RU/resources.resjson
  Tasks/AzureFileCopyV5/Strings/resources.resjson/zh-CN/resources.resjson
  Tasks/AzureFileCopyV5/Strings/resources.resjson/zh-TW/resources.resjson
  Tasks/AzureFileCopyV5/Tests/L0.ts
  Tasks/AzureFileCopyV5/Tests/L0AddAzureVMCustomScriptExtension.ps1
  Tasks/AzureFileCopyV5/Tests/L0CheckContainerNameAndArgs.ps1
  Tasks/AzureFileCopyV5/Tests/L0CopyFilesParallelyToAzureVMs.ps1
  Tasks/AzureFileCopyV5/Tests/L0CopyFilesSequentiallyToAzureVMs.ps1
  Tasks/AzureFileCopyV5/Tests/L0CopyFilesToAzureVMsFromStorageContainer.ps1
  Tasks/AzureFileCopyV5/Tests/L0DoesAzureVMMatchTagFilter.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetAzureUtility.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetAzureVMResourcesProperties.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetAzureVMsCredentials.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetFilteredAzureRMVmsInResourceGroup.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetFilteredAzureVmsInResourceGroup.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetFrontEndPorts.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetMachineBasedFilteredAzureVMs.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetMachineNameFromId.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetMachinesFqdnForLB.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetRMVMConnectionDetailsInRG.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetStorageAccountType.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetStorageKey.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetTagBasedFilteredAzureVMs.ps1
  Tasks/AzureFileCopyV5/Tests/L0GetblobStorageEndpoint.ps1
  Tasks/AzureFileCopyV5/Tests/L0IsWinRMCustomScriptExtensionExists.ps1
  Tasks/AzureFileCopyV5/Tests/L0UploadFilesToAzureContainer.ps1
  Tasks/AzureFileCopyV5/Tests/L0UtilityThrowError.ps1
  Tasks/AzureFileCopyV5/Tests/L0ValidateAzurePSVersion.ps1
  Tasks/AzureFileCopyV5/Tests/L0ValidateCustomScriptExecutionStatus.ps1
  Tasks/AzureFileCopyV5/Tests/MockHelper.ps1
  Tasks/AzureFileCopyV5/Tests/MockVariable.ps1
  Tasks/AzureFileCopyV5/ThirdPartyNotices.txt
  Tasks/AzureFileCopyV5/Utility.ps1
  Tasks/AzureFileCopyV5/icon.png
  Tasks/AzureFileCopyV5/icon.svg
  Tasks/AzureFileCopyV5/make.json
  Tasks/AzureFileCopyV5/package-lock.json
  Tasks/AzureFileCopyV5/package.json
  Tasks/AzureFileCopyV5/task.json
  Tasks/AzureFileCopyV5/task.loc.json
  Tasks/AzureFileCopyV5/tsconfig.json
  make-options.json
Labels: environment:enhancement

#15888 Fix remaining dependabot alerts
  Tasks/FtpUploadV1/package-lock.json
  Tasks/FtpUploadV1/task.json
  Tasks/FtpUploadV1/task.loc.json
  Tasks/GradleV2/package-lock.json
  Tasks/GradleV2/task.json
  Tasks/GradleV2/task.loc.json
  Tasks/NodeToolV0/package-lock.json
  Tasks/NodeToolV0/task.json
  Tasks/NodeToolV0/task.loc.json
Labels: bug, enhancement

#15896 Fix vulnerabilities
  Tasks/ANTV1/package-lock.json
  Tasks/ANTV1/task.json
  Tasks/ANTV1/task.loc.json
  Tasks/AndroidSigningV2/package-lock.json
  Tasks/AndroidSigningV2/task.json
  Tasks/AndroidSigningV2/task.loc.json
  Tasks/AndroidSigningV3/package-lock.json
  Tasks/AndroidSigningV3/task.json
  Tasks/AndroidSigningV3/task.loc.json
  Tasks/ArchiveFilesV2/package-lock.json
  Tasks/ArchiveFilesV2/task.json
  Tasks/ArchiveFilesV2/task.loc.json
  Tasks/BashV3/package-lock.json
  Tasks/BashV3/task.json
  Tasks/BashV3/task.loc.json
  Tasks/CMakeV1/package-lock.json
  Tasks/CMakeV1/task.json
  Tasks/CMakeV1/task.loc.json
  Tasks/CUrlUploaderV2/package-lock.json
  Tasks/CUrlUploaderV2/task.json
  Tasks/CUrlUploaderV2/task.loc.json
  Tasks/CmdLineV2/package-lock.json
  Tasks/CmdLineV2/task.json
  Tasks/CmdLineV2/task.loc.json
  Tasks/CocoaPodsV0/package-lock.json
  Tasks/CocoaPodsV0/task.json
  Tasks/CocoaPodsV0/task.loc.json
  Tasks/CondaEnvironmentV0/Tests/L0_conda.ts
  Tasks/CondaEnvironmentV0/Tests/L0_conda_internal.ts
  Tasks/CopyFilesOverSSHV0/package-lock.json
  Tasks/CopyFilesOverSSHV0/package.json
  Tasks/CopyFilesOverSSHV0/task.json
  Tasks/CopyFilesOverSSHV0/task.loc.json
  Tasks/DecryptFileV1/package-lock.json
  Tasks/DecryptFileV1/task.json
  Tasks/DecryptFileV1/task.loc.json
  make-util.js
  make.js
  package-lock.json
  package.json
Labels: enhancement

#15899 Update JaCoCo Maven plugin to ver. 0.8.7
  common-npm-packages/codecoverage-tools/codecoverageconstants.ts
  common-npm-packages/codecoverage-tools/package-lock.json
  common-npm-packages/codecoverage-tools/package.json
Labels: Task: Maven

#15928 [Maven tasks] Bump the codecoverage-tools package at the dependencies
  Tasks/MavenV2/package-lock.json
  Tasks/MavenV2/package.json
  Tasks/MavenV2/task.json
  Tasks/MavenV2/task.loc.json
  Tasks/MavenV3/package-lock.json
  Tasks/MavenV3/package.json
  Tasks/MavenV3/task.json
  Tasks/MavenV3/task.loc.json
Labels: bug, Area: ABTT, Task: Maven

#15881 [FtpUploadV2] Resolve dependabot alert about shelljs
  Tasks/FtpUploadV2/Tests/L0.ts
  Tasks/FtpUploadV2/Tests/L0NoClean.ts
  Tasks/FtpUploadV2/Tests/L0NoFilePatterns.ts
  Tasks/FtpUploadV2/Tests/L0NoFilesFound.ts
  Tasks/FtpUploadV2/Tests/L0NoHostName.ts
  Tasks/FtpUploadV2/Tests/L0NoPreservePaths.ts
  Tasks/FtpUploadV2/Tests/L0NoProtocol.ts
  Tasks/FtpUploadV2/Tests/L0NoRemotePath.ts
  Tasks/FtpUploadV2/Tests/L0NoRootFolder.ts
  Tasks/FtpUploadV2/Tests/L0NoServerEndpoint.ts
  Tasks/FtpUploadV2/Tests/L0NoTrustSSL.ts
  Tasks/FtpUploadV2/Tests/L0Successful.ts
  Tasks/FtpUploadV2/Tests/package-lock.json
  Tasks/FtpUploadV2/Tests/package.json
  Tasks/FtpUploadV2/ftpuploadtask.ts
  Tasks/FtpUploadV2/package-lock.json
  Tasks/FtpUploadV2/package.json
  Tasks/FtpUploadV2/task.json
  Tasks/FtpUploadV2/task.loc.json
Labels: bug, enhancement
