Repository microsoft/azure-pipelines-tasks, pull requests merged in 2022-03, with the labels that each got.

#15972 Fix shelljs vulnerability for tasks
  Tasks/ArchiveFilesV2/package-lock.json
  Tasks/ArchiveFilesV2/task.json
  Tasks/ArchiveFilesV2/task.loc.json
  Tasks/BashV3/package-lock.json
  Tasks/BashV3/task.json
  Tasks/BashV3/task.loc.json
  Tasks/CMakeV1/package-lock.json
  Tasks/CMakeV1/task.json
  Tasks/CMakeV1/task.loc.json
  Tasks/CocoaPodsV0/package-lock.json
  Tasks/CocoaPodsV0/task.json
  Tasks/CocoaPodsV0/task.loc.json
Labels: bug

#15820 [UsePythonV0] Download python from registry
  Tasks/UsePythonVersionV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/UsePythonVersionV0/Tests/L0.ts
  Tasks/UsePythonVersionV0/Tests/L0DownloadsFromRegistryUbuntu.ts
  Tasks/UsePythonVersionV0/Tests/L0DownloadsFromRegistryWindows.ts
  Tasks/UsePythonVersionV0/Tests/L0DownloadsUnstable.ts
  Tasks/UsePythonVersionV0/Tests/L0FailsWhenVersionIsMissing.ts
  Tasks/UsePythonVersionV0/Tests/data/versions-manifest.json
  Tasks/UsePythonVersionV0/installpythonversion.ts
  Tasks/UsePythonVersionV0/interfaces.ts
  Tasks/UsePythonVersionV0/main.ts
  Tasks/UsePythonVersionV0/osutil.ts
  Tasks/UsePythonVersionV0/package-lock.json
  Tasks/UsePythonVersionV0/package.json
  Tasks/UsePythonVersionV0/task.json
  Tasks/UsePythonVersionV0/task.loc.json
  Tasks/UsePythonVersionV0/usepythonversion.ts
  Tasks/UsePythonVersionV0/versionspec.ts
Labels: enhancement

#15883 Move notifications about Courtesy push activities from Slack to MS Teams
  azure-pipelines.yml
  ci/courtesy-push.yml
  ci/courtesy-push/open-courtesy-push-pull-request.js
  ci/courtesy-push/send-notification.ps1
Labels: enhancement

#16014 Revert "[UsePythonV0] Download python from registry (#15820)"
  Tasks/UsePythonVersionV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/UsePythonVersionV0/Tests/L0.ts
  Tasks/UsePythonVersionV0/Tests/L0DownloadsFromRegistryUbuntu.ts
  Tasks/UsePythonVersionV0/Tests/L0DownloadsFromRegistryWindows.ts
  Tasks/UsePythonVersionV0/Tests/L0DownloadsUnstable.ts
  Tasks/UsePythonVersionV0/Tests/L0FailsWhenVersionIsMissing.ts
  Tasks/UsePythonVersionV0/Tests/data/versions-manifest.json
  Tasks/UsePythonVersionV0/installpythonversion.ts
  Tasks/UsePythonVersionV0/interfaces.ts
  Tasks/UsePythonVersionV0/main.ts
  Tasks/UsePythonVersionV0/osutil.ts
  Tasks/UsePythonVersionV0/package-lock.json
  Tasks/UsePythonVersionV0/package.json
  Tasks/UsePythonVersionV0/task.json
  Tasks/UsePythonVersionV0/task.loc.json
  Tasks/UsePythonVersionV0/usepythonversion.ts
  Tasks/UsePythonVersionV0/versionspec.ts
Labels: bug

#15458 Add braces to '-and' in if statements, for the correct function handling
  Tasks/AzureCloudPowerShellDeploymentV1/task.json
  Tasks/AzureCloudPowerShellDeploymentV1/task.loc.json
  Tasks/AzureFileCopyV1/task.json
  Tasks/AzureFileCopyV1/task.loc.json
  Tasks/AzureFileCopyV2/task.json
  Tasks/AzureFileCopyV2/task.loc.json
  Tasks/AzureFileCopyV3/task.json
  Tasks/AzureFileCopyV3/task.loc.json
  Tasks/AzureFileCopyV4/task.json
  Tasks/AzureFileCopyV4/task.loc.json
  Tasks/AzureFileCopyV5/task.json
  Tasks/AzureFileCopyV5/task.loc.json
  Tasks/AzurePowerShellV2/task.json
  Tasks/AzurePowerShellV2/task.loc.json
  Tasks/AzurePowerShellV3/task.json
  Tasks/AzurePowerShellV3/task.loc.json
  Tasks/AzurePowerShellV4/task.json
  Tasks/AzurePowerShellV4/task.loc.json
  Tasks/AzurePowerShellV5/task.json
  Tasks/AzurePowerShellV5/task.loc.json
  Tasks/Common/VstsAzureHelpers_/Utility.ps1
  Tasks/SqlAzureDacpacDeploymentV1/task.json
  Tasks/SqlAzureDacpacDeploymentV1/task.loc.json
Labels: bug

#15917 Move notifications about Tasks Localization PR from Slack to MS Teams - Part 1
  Localize/localize-pipeline.yml
  ci/localization-updates/send-notifications.ps1
  ci/open-pullrequest.ps1
Labels: enhancement

#15918 Move notifications about Tasks Localization PR from Slack to MS Teams - Part 2
  ci/localization-updates/send-notifications.ps1
  ci/open-pullrequest.ps1
Labels: enhancement

#16083 Add symbol retention field to PublishSymbolsV2
  Tasks/PublishSymbolsV2/Publish-Symbols.ps1
  Tasks/PublishSymbolsV2/PublishSymbols.ps1
  Tasks/PublishSymbolsV2/Strings/resources.resjson/en-US/resources.resjson
  Tasks/PublishSymbolsV2/task.json
  Tasks/PublishSymbolsV2/task.loc.json
Labels: bug, Area: ArtifactsCore
