Repository microsoft/azure-pipelines-tasks, pull requests merged in 2022-05, with the labels that each got.

#16188 Replaced request with typed-rest-client package
  Tasks/DownloadBuildArtifactsV0/package-lock.json
  Tasks/DownloadGitHubNpmPackageV1/npminstall.ts
  Tasks/DownloadGitHubNpmPackageV1/package-lock.json
  Tasks/DownloadGitHubNpmPackageV1/package.json
  Tasks/DownloadGitHubNpmPackageV1/task.json
  Tasks/DownloadGitHubNpmPackageV1/task.loc.json
Labels: enhancement

#16321 Update pypy3 default version to 3.9
  Tasks/UsePythonVersionV0/Strings/resources.resjson/en-US/resources.resjson
  Tasks/UsePythonVersionV0/task.json
  Tasks/UsePythonVersionV0/task.loc.json
  Tasks/UsePythonVersionV0/usepythonversion.ts
Labels: bug

#16023 [Maven] Implement the SpotBugs plugin for the maven task
  Tasks/MavenV3/Strings/resources.resjson/en-US/resources.resjson
  Tasks/MavenV3/Tests/L0.ts
  Tasks/MavenV3/Tests/L0SpotbugsPlugin.ts
  Tasks/MavenV3/Tests/L0SpotbugsWithResultPublishing.ts
  Tasks/MavenV3/Tests/TestUtils.ts
  Tasks/MavenV3/maventask.ts
  Tasks/MavenV3/package-lock.json
  Tasks/MavenV3/package.json
  Tasks/MavenV3/spotbugsTool/index.ts
  Tasks/MavenV3/spotbugsTool/publishSpotbugsReport.ts
  Tasks/MavenV3/spotbugsTool/spotbugs.ts
  Tasks/MavenV3/task.json
  Tasks/MavenV3/task.loc.json
  Tasks/MavenV3/utils/addPropToJson.ts
  Tasks/MavenV3/utils/convertJsonToXml.ts
  Tasks/MavenV3/utils/convertXmlToJson.ts
  Tasks/MavenV3/utils/fileUtils.ts
  Tasks/MavenV3/utils/index.ts
  Tasks/MavenV3/utils/mavenutil.ts
  Tasks/MavenV3/utils/newMavenUtils.ts
  Tasks/MavenV3/utils/removeBom.ts
Labels: Area: ABTT, Task: Maven

#16197 Updated dependencies for AzureFunctionAppV1
  Tasks/AzureFunctionAppV1/package-lock.json
  Tasks/AzureFunctionAppV1/package.json
  Tasks/AzureFunctionAppV1/task.json
  Tasks/AzureFunctionAppV1/task.loc.json
Labels: enhancement, environment:external-dependency
